### ISSUE TITLE
Have an edit verb to have interactive update on many resources.

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1005]
## Description

Let's suppose that I want to edit several properties of a single resource. Let's say the name of an instance and its description. So far, I would need to type explicitly the name of the argument without mistake and the new value.

It would be handier to have an edit function that will output a YAML description of the resource with only the field I can edit. By doing so, I can edit potentially complex data structures such as LB backend/frontend rules using my favorite editor. 

## How this functionality would be exposed

`scw instance server edit 11111111-1111-1111-1111-111111111111`

I would get something like:

```
---
server:
  id: fa37ff62-4665-4b94-93bf-385d264a7b4d
  name: pouet
  tags: []
...
```

## References

- This is very similar to the kubectl edit command that allows a user to edit a resource using an editor, save the file and apply it to a Kubernetes cluster.

**Comment by jerome-quere** [comment]
Duplicate #1171
