### ISSUE TITLE
Enable zone and architecture filtering for marketplace list and get

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1009]
## Description

As a developer looking for finding the UUID of an image from the marketplace, I would like to have filtering of my results depending on the zone or of the specific architecture I want.

## How this functionality would be exposed

```
scw marketplace image list label=prestashop zone=fr-par-1  arch=x86_64
```

This should give me the correct UUID that I could use directly when instantiating a server. 

## Version

version     2.0.0-beta.2&#43;dev
build-date  unknown
go-version  go1.14.2
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
We prefer to rely on future template system to handle this type of usecase
