### ISSUE TITLE
instance create should accept a cloud-init script value

### ISSUE THREAD

**Issue by karibou** [scaleway/scaleway-cli#1072]
## Description
`instance create` should accept `cloud-init=` option to provide a cloud-init script

## How this functionality would be exposed
Add `cloud-init` option

## References
Adding a cloud-init script will require a PATCH to the API after the POST to create the server as it is not possible to POST to /servers with the cloud-init script in one POST. The sequence of actions would be :
1: POST to /servers to create the server
2: PATCH to /servers/{id}/user_data/cloud-init to add the cloud-init script

## Version

version     2.0.0-beta.3
build-date  2020-06-03T01:45:27PM
go-version  go1.14.3
git-branch  new-release
git-commit  522d322a
go-arch     amd64
go-os       linux

**Comment by remyleone** [comment]
Fixed
