### ISSUE TITLE
Have more helpful message when doing an image create

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1105]
## Description

When I do an image create with a snapshot id that is not known: 

```
scw image create snapshot-id=11111111-1111-1111-1111-111111111111 arch=x86_64
Cannot find resource '' with ID '11111111-1111-1111-1111-111111111111'
```

## How this functionality would be exposed

```
scw image create snapshot-id=11111111-1111-1111-1111-111111111111 arch=x86_64
Cannot find a snapshot with ID '11111111-1111-1111-1111-111111111111'
```

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.3
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
This error is sent by the instance API. This should be handled API in the API

**Comment by Codelax** [comment]
This is a lack of consistency in API errors. Issue has been transfered to instance team

**Comment by Codelax** [comment]
Work has been done to change errors.
```
❯ scw instance image create snapshot-id=11111111-1111-1111-1111-111111111111 arch=x86_64   
Unknown snapshot: 11111111-1111-1111-1111-111111111111
```
