### ISSUE TITLE
Make the environment variable name more explicit

### ISSUE THREAD

**Issue by moul** [scaleway/scaleway-cli#111]

**Comment by moul** [comment]
@QuentinPerez, can you list current environment variables ?

**Comment by QuentinPerez** [comment]
Currently we have:
- SCW_COMPUTE_API
- SCW_ACCOUNT_API
- SCW_METADATA_API
- SCW_MARKETPLACE_API
- SCW_VERBOSE_API
- SCW_TLSVERIFY
- SCW_SENSITIVE
- SCW_COMMERCIAL_TYPE
- SCW_TARGET_ARCH
- SCW_TARGET_REGION
- SCW_NOCHECKVERSION
- SCW_GATEWAY
- SCW_GOTTY_URL
- scaleway_api_endpoint
- DEBUG
- exec_secure

**Comment by moul** [comment]
Ok cool, so basically we can let `DEBUG` as it is, remove `scaleway_api_endpoint` and rename `exec_secure` to `SCW_SECURE_EXEC`

**Comment by moul** [comment]
See #312
