### ISSUE TITLE
Add a -f (--force) on all delete action

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1110]
## Description

Sometimes I want to delete a resource but this resource might have been already deleted somewhere else. I would like to have a --force that will return 0 whether the resource is deleted or not present. Just like a `rm -f`

## How this functionality would be exposed

`scw account ssh-key remove -f 11111111-1111-1111-1111-111111111111`

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.3
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
What would be the use case for such feature. You could simply ignore error code
