### ISSUE TITLE
scw instance server list does not display all fields

### ISSUE THREAD

**Issue by karibou** [scaleway/scaleway-cli#1113]
## Description:
```
scw instance server list
```
does not properly display all fields even when window is resized to a small display

## How to reproduce:

This is not systematic but I can reproduce it rather often.
Resize the terminal (Ctrl - minus) to a small display and issue scw instance server list
Only a few fields will be displayed

### Command attempted
scw instance server list

### Expected Behavior
All fields that can fit on the window should be displayed

### Actual Behavior
Not all fields are displayed
## Version
51b656e3-4865-41e8-adbc-0c45bdd780db
version     2.0.0-beta.4
build-date  2020-06-08T03:33:48PM
go-version  go1.14.3
git-branch  new-release
git-commit  620ac25e
go-arch     amd64
go-os       linux
![cli_v2_fields](https://user-images.githubusercontent.com/1553319/85112578-1d5ed400-b216-11ea-9c6e-e6a41526f844.jpg)

**Comment by kindermoumoute** [comment]
This is a design choice:

```bash
# interactive mode adapt to your terminal width
scw instance server list

# piping disable interactive mode, removing colors and showing all fields
scw instance server list | cat
```

This is still debatable if too many people find this behavior confusing.

**Comment by karibou** [comment]
Hello,
If you look closely at the screenshot, almost half of the screen is empty and not filled with the extra field.
I would expect to see extra fields if I make my xterm size smaller.
I must admit that this behavior is erratic as it does happens to work as expected sometimes.
I'll try to identify what makes things change :

![cli_v2_fields_2](https://user-images.githubusercontent.com/1553319/85255126-f268c000-b461-11ea-9382-cda66a4286f7.jpg)

**Comment by jerome-quere** [comment]
#1158 will probably solved this issue

**Comment by jerome-quere** [comment]
With #1158 you can use `-o human=ID,Name,...` to select column you want to print.
