### ISSUE TITLE
Add a cookbook method to use pgloader and the cli to load data from sources into a managed database

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1132]
## Description

Add a cookbook method to use pgloader and the cli to load data from sources into a managed database

https://pgloader.io/

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.4
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
Cookbooks are more fitted for CLI centric content this may be a good tutorial
