### ISSUE TITLE
Support pgsql:// url generation for a given user/database

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### How I imagine scw could expose this functionality

`scw rdb user get 11111111-1111-1111-1111-111111111111 db=foobar`

In this return value I should have available the URL to connect to the db "pgsql://username@ip:/foobar" ...
Or if I got a specific database

`scw rdb db get 11111111-1111-1111-1111-111111111111 user=foobar`

"pgsql://foobar@1.2.3.4/db"

**Comment by jerome-quere** [comment]
maybe this could be embedded as a field in `get database`

**Comment by jerome-quere** [comment]
We need to have a Engine familly to determine if we have a pgsql:// or mysql:// uri
