### ISSUE TITLE
Add a connect verb for a database

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to connect directly to a database, this command would exec to psql ou mysql installed locally with the right parameters.

### How I imagine scw could expose this functionality

`scw rdb database connect`

This command take also in argument the path to a local shell command in case the default one for each database is not working.
This allow a user to use docker container to have a command line util that match the right database version.

**Comment by jerome-quere** [comment]
For the first iteration, we should support this feature as a simple helper for golden scenario. Let's handle problems link with pgsql version or docker container in the next iteration.
