### ISSUE TITLE
Have a default for preparing logs with default date

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1153]
## Description:

I get an internal error when I sent a request with malformed data.
As a default, I would expect to have all the available logs till the current date prepared. 

## How to reproduce:

$ go run ./cmd/scw/main.go rdb log prepare ca6271c4-5182-4627-81c2-3d8a8542585b   
Internal error

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.4
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
All log could be a lot. Maybe we should consider something like last 3 months ?

**Comment by jerome-quere** [comment]
Requires #1160

**Comment by jerome-quere** [comment]
If there are predefined default on the API side we should sent `nil` and let the API decide.

**Comment by Mia-Cross** [comment]
I was unable to reproduce the issue as of today.

The exact command `go run ./cmd/scw/main.go rdb log prepare ca6271c4-5182-4627-81c2-3d8a8542585b` doesn't result in `Internal error` but `Unknown argument 'ca6271c4-5182-4627-81c2-3d8a8542585b'`.

And `go run ./cmd/scw/main.go rdb log prepare instance-id=ca6271c4-5182-4627-81c2-3d8a8542585b` prepares the log as expected.
