### ISSUE TITLE
List all available metrics in rdb instance

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1161]
## Description

As a user, I would like to know what metrics are available for a given instance. 

## How this functionality would be exposed

scw rdb instance-metrics list

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.4
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
Blocked by #1172

**Comment by remyleone** [comment]
Superseeded by cockpit
