### ISSUE TITLE
Add a way to list and have completion on custom settings

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1165]
## Description

As a user that want to customize some settings, I would like to:

- Have a list of all the settings I can customize for a given engine
- Have short documentation about what given settings is about with a link to the reference documentation
- Have completion on it while I update from the command line

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.4
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
Requires #1171

**Comment by jerome-quere** [comment]
We need to be careful as autocomplete with values from the API is quite slow and can be frustrating
