### ISSUE TITLE
add support for generating markdown documentation from the CLI

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1169]
## Description

Some users want to navigate the example from a web page. We could generate one like this on Github.
This page would be made from the different documentation strings (examples, see also) that would be put together in a markdown file that would be added to the repository in the docs/ folder.

## Version

version     2.0.0-beta.4&#43;dev
build-date  unknown
go-version  go1.14.4
git-branch  unknown
git-commit  unknown
go-arch     amd64
go-os       darwin

**Comment by jerome-quere** [comment]
We should not limit ourself to the example but also generate documentation for commands
