### ISSUE TITLE
Implement tooling to edit complex data in a text editor

### ISSUE THREAD

**Issue by jerome-quere** [scaleway/scaleway-cli#1171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some data like ACL in database or security group are hard to manipulate with CLI command. We should implement tooling that allow this data to be edited in a visual editor and apply on exist. This could be yaml base or other.

This feature would be very similar to the `kubectl edit` feature that takes a Kubernetes resource, open it in an editor and on saving reapply it.

<https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/edit/edit.go>

**Comment by kindermoumoute** [comment]
Relates to https://github.com/scaleway/scaleway-cli/issues/925
