### ISSUE TITLE
When listing k8s cluster I would like to find information about pools and nodes.

### ISSUE THREAD

**Issue by jerome-quere** [scaleway/scaleway-cli#1203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When listing k8s cluster it would be nice if I could have number of node and number of pools. We would need API update

**Comment by jerome-quere** [comment]
What do you think @Sh4d1  ?

**Comment by Sh4d1** [comment]
I think we won't do it. We removed the node count between the v1beta4 and v1 of the API, not to add it again a few months later :sweat_smile: 

Though we'll soon change some things in the API that may bring this count back. So not now, maybe later :smile:
