### ISSUE TITLE
Make instance user-data set/get/delete should not have positional argument

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1232]
## Description

We try to only use postional parameter when the ID is directly related to the command type

Example:
```
scw instance server get my-server-uuid <= This is a server ID so OK 
scw instance user-data list server-id=XXXXX <= Not positional as id is not a user-data ID
```

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.4
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by remyleone** [comment]
@karibou What is your opinion about it? We would like to stay consistent across all commands.

**Comment by karibou** [comment]
Hi,
I'm on holiday. Back on that when I'm back.
...Louis

Le mer. 29 juil. 2020 à 15:53, Rémy Léone <notifications@github.com> a
écrit :

**Comment by karibou** [comment]
Hi,
sorry for not replying sooner.
LGTM, make sense in that context.
...Louis
