### ISSUE TITLE
have a way to test for dead links in markdown documentation in the repo

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1247]
## Description

We could use the same github action workflow that exists in the terraform provider:
<https://github.com/scaleway/terraform-provider-scaleway/blob/master/.github/workflows/documentation.yml#L18-L28>

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.4
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jerome-quere** [comment]
We should find a way to integrate this in the CI
