### ISSUE TITLE
Have a command to quickly add an instance to a load balancer

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1256]
## Description

As a user, I would like to register a given instance to a given load balancer.

`scw lb backend register 11111111-1111-1111-1111-111111111111 port=80`

And this would automatically gather the IP of the instance, add it to the backend with the right port.

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jerome-quere** [comment]
The idea is cool but:

- Will this be much simpler than adding the IP?
- What happens if an instance does not have public IP?
- Does it add public or private IP? 
- This could be confusing as it could lead the user to think if the instance IP change the LB will be automatically updated.

**Comment by remyleone** [comment]
- Let's suppose that the IP change for any reason, the ID of the instance remains the same. So the ID is more durable than the IP. Plus if tomorrow we add IPv6 we could have the import that takes care of both IPv4 and IPv6 at the same time.
- We can add the private IP by doing so, we are sure that it always exists
- I would say private
- It is an importer, not a controller, if the IP changes a user just has to run the exact same command and remove the old backend.
