### ISSUE TITLE
Import a security group and apply it as an ACL

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1257]
## Description

How can I import a security group to make it an ACL for load balancer ?
Once I got a security group that works for a given instance, I don't want to copy manually all this configuration to make it an ACL again. I would like to import it and make an ACL out of it.

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jerome-quere** [comment]
What would be a real use case for this?  It seems strange to me as this is not the same use case. Plus the feature is no the same what if the security group has deny rules for example.
