### ISSUE TITLE
Add a warning to not manually edit load-balancer that got a tag `kapsule-`

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1258]
## Description

Load balancer managed by Kapsule got their settings set up by Kapsule automatically. Any change applied to those load balancers will be overwritten by Kapsule regularly.
We should add a warning to not edit those load-balancer as changes will be overwritten

## Version

Version    2.0.0-beta.4&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jerome-quere** [comment]
Where would this warning be added ? In the list ? In the get ?
