### ISSUE TITLE
Use @ to load content from a file in an arg

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1287]
## Description

As a user, I would like to pass the content of file to a command in scw. For instance, to load an SSH key or a TLS certificate.
It would also be nice to have autocomplete support for it.

## Version

Version    2.0.0&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by jtherin** [comment]
up! 😅

**Comment by Sh4d1** [comment]
Closing in favour of #1518
