### ISSUE TITLE
`scw instance server list` prints only instances' IDs and no other info.

### ISSUE THREAD

**Issue by Ignacy-s** [scaleway/scaleway-cli#1323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## NVM it works now. It must have been a momentarily madness.
Please close the issue :)
## Command attempted

`scw instance server list`

### Expected Behavior
It used to print more info next to the instance ID, like name, server type etc.

### Actual Behavior
Only the IDs got printed.
[vagrant@portainer-test vagrant]$ scw instance server list
ID
XXXXX-XXXX-XXXX-XXXXXX
XXXXX-XXXX-XXXX-XXXXXX
XXXXX-XXXX-XXXX-XXXXXX
XXXXX-XXXX-XXXX-XXXXXX

## More info
Version    2.0.0
BuildDate  2020-07-16T07:53:40AM
GoVersion  go1.14.4
GitBranch  new-release
GitCommit  f861b9d9
GoArch     amd64
GoOS       linux

P.S. Just realised I can tab-complete instance IDs. The scw tool is now awesome!

**Comment by remyleone** [comment]
Thanks a lot for using the CLI :) if you have other comments/feedback/questions, don't hesitate to open an issue :)
