### ISSUE TITLE
Have an option to disable all region/zone/products checks performed by the CLI

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1324]
## Description

This could be useful in the CLI to access internal zone that are not exposed to the public or AZ that are not out yet.

## Version

Version    2.0.0&#43;dev
BuildDate  unknown
GoVersion  go1.14.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by kindermoumoute** [comment]
AFAIK the only blocking checks happen when the format of a zone / region in invalid. But you can already use the cli with any zone that respect these formats, e.g.: `plop-blablabla-12` is a valid zone.

Do you have any particular example in mind that don't work?

**Comment by Sh4d1** [comment]
https://github.com/scaleway/scaleway-cli/blob/master/internal/namespaces/instance/v1/instance_cli.go#L291 here for instance

**Comment by kindermoumoute** [comment]
@Sh4d1 these values are only used for completion and documentation purposes. You can still provide another zone / region than these if you want.

Closing this ticket since `scw instance server-type list zone=hi-bla-5` does work (and returns 404 of course)
