### ISSUE TITLE
Use project_id in scw instance server create

### ISSUE THREAD

**Issue by QuentinBrosse** [scaleway/scaleway-cli#1517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`$ scw instance server create image=ubuntu_bionic`

### Expected Behavior

Create a server wihout warning.

### Actual Behavior

```
$ scw instance server create image=ubuntu_bionic
The argument 'organization-id' is deprecated, more info with: scw instance server create --help
```

## More info

```
$ scw version
Version    2.2.2
BuildDate  unknown
GoVersion  go1.15.3
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin
```

**Comment by Codelax** [comment]
```
 ± scw instance server create image=ubuntu_bionic
ID                          5fe2511f-dcfd-438a-9931-ce41bf543d77
Name                        cli-srv-pensive-khayyam
```

Doesn't happen anymore
