### ISSUE TITLE
Improve scw instance server [create|update] cloud-init argument

### ISSUE THREAD

**Issue by QuentinBrosse** [scaleway/scaleway-cli#1518]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some thought about the `cloud-init` argument:
- [ ] Allow to pass a file path in the `cloud-init` argument

Today this argument takes the content of the config, it's not very convenient:

```console
$ scw instance server create image=ubuntu-bionic cloud-init="#cloud-config                                                                                              
	users:
	- name: demo"

# or

$ scw instance server create image=ubuntu-bionic cloud-init=$(cat cloud-init-config.yaml)
```

What do ou think about somethink like this?

```console
$ scw instance server create image=ubuntu-bionic cloud-init="./cloud-init-config.yaml"
```

As an example, [here is our the v1 CLI was handling this](https://www.scaleway.com/en/docs/how-to-use-cloud-init-to-configure-your-server-at-first-boot/#-Provisioning-your-Instance-with-CloudInit)

- [ ] Add tests for this argument

- [ ] Add example and improve argument shot [in the doc](https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/instance.md#create-server)

- [ ] Update the [How to use Cloud-Init to configure your server at first boot tuto](https://www.scaleway.com/en/docs/how-to-use-cloud-init-to-configure-your-server-at-first-boot/#-Provisioning-your-Instance-with-CloudInit) with the new v2 CLI command.

**Comment by QuentinBrosse** [comment]
Maybe with this syntax https://github.com/scaleway/scaleway-cli/issues/1287

**Comment by Sh4d1** [comment]
Yes, the implementation with `@` sounds better
