### ISSUE TITLE
Issue with authorization

### ISSUE THREAD

**Issue by kpologovoy** [scaleway/scaleway-cli#1521]
We would like  to use cli

But have an error during authorization process again and again after command   scw init

Enter a valid secret-key or an email: xxxxxxxxxxxxxxxxxxxxxx
Enter your password:
Wrong username or password.
Enter your password:
Wrong username or password.
Enter your password:

We have tried to reset password and re-login but have the same issue.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by remyleone** [comment]
A secret key is not your password. In case you don't succeed to use this command, feel free to create a configuration file manually https://github.com/scaleway/scaleway-sdk-go/blob/master/scw/README.md
