### ISSUE TITLE
Add documentation about adding instances automatically from a tag in a load balancer backend

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by willoucom** [comment]
Here is a small script to replace backend ip by any instance by tag

```
#!/bin/bash

set -e

LB_NAME=$1
TAG=$2

cmd_f_help () {
  cat << _HELP_
Add Instance private IP to LB of your choice

  Usage :
    First parameter: Name of the load balancer
    Second parameter: Tag of your VM
_HELP_
}

if [ $# -lt 2 ]
then
    cmd_f_help
    exit 1
fi

LB_ID=$(scw lb lb list name="${LB_NAME}" -o template="{{ .ID }}")
LB_BACKEND=$(scw lb backend list lb-id="${LB_ID}" -o template="{{ .ID }}")
INSTANCE_IP=$(scw instance server list tags.0="${TAG}"  -o template="{{ .PrivateIP }}")

i=0
IPS=""
for variable in $INSTANCE_IP
do
    IPS="${IPS} server-ip.$i=$variable"
    ((i=i+1))
done

for BACKEND in $LB_BACKEND
do
    scw lb backend set-servers $BACKEND $IPS
done
```

**Comment by remyleone** [comment]
This could also be a feature of a backend spécific command
