### ISSUE TITLE
Can't delete image with `scw instance image delete image_id`

### ISSUE THREAD

**Issue by AgileNix** [scaleway/scaleway-cli#1532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw instance image delete b57e72c1-f394-4546-z141-78233b6e`

### Expected Behavior

Image successfully deleted or proper error.

### Actual Behavior

Invalid arguments 'image_id'

Details:
- 'image_id' does not respect constraints

Hint:
B57e72c1-f394-4546-z141-78233b6e is not a valid UUID.

## More info

Image id in the example was changed due to security constraints. 
Seems that the first letter of the `image_id` was capitalized unexpectedly which caused the error.

**Comment by Sh4d1** [comment]
Hum looks like you have an upper case letter in your uuid. Works fine for me with a correct uuid

**Comment by QuentinBrosse** [comment]
@Sh4d1 the `B` transformed to uppercase by the human output serializer.

**Comment by Sh4d1** [comment]
Indeed 😅 though there is `z` in the uuid which should not be there :p

**Comment by QuentinBrosse** [comment]
@AgileNix `b57e72c1-f394-4546-z141-78233b6e` is an invalid UUID, 4 characters are mission at the end.

**Comment by AgileNix** [comment]
@QuentinBrosse indeed, I had an issue with the regex that pulled the UUID from the list of all images.

Btw, is there a more efficient way of creating regular snapshots and deleting old ones than what I'm currently doing?
1) create a backup, use server name, and current date to name it
2) get all images and use regex to find the image id that I'd like to delete
3) delete old image based on the uuid from step 2
