### ISSUE TITLE
Cannot set user-data content from file

### ISSUE THREAD

**Issue by t0k4rt** [scaleway/scaleway-cli#1556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

Scaleway provides documentation about testing cloud init configurations
https://www.scaleway.com/en/docs/how-to-use-cloud-init-to-configure-your-server-at-first-boot/

The example show this usage of the scaleway cli:
`scw _userdata {server Id} cloud-init=@/path/to/cloud-config-file`

This example suggest you can  upload a file ("@/file") for the key cloud-init 

This behavior does not seems to exist in the latest scaleway cli.

The new cli does not allow this, this command won't upload the file as content:

`scw instance user-data set {server id} key=cloud-init content=@./cloudtest.yml`

### Expected Behavior

```
echo "runcmd:\n  - [ cloud-init, status]" > ./cloudtest.yml  
scw instance user-data set {server id} key=cloud-init content=@./cloudtest.yml
scw instance user-data get {server id} key=cloud-init
# should return
runcmd:
  - [ cloud-init, status]
```

### Actual Behavior

```
echo "runcmd:\n  - [ cloud-init, status]" > ./cloudtest.yml  
scw instance user-data set {server id} key=cloud-init content=@./cloudtest.yml
scw instance user-data get {server id} key=cloud-init
# returns
@./cloudtest.yml
```

## More info

```
scw version                                                                    
Version    2.0.0
BuildDate  2020-07-16T07:53:40AM
GoVersion  go1.14.4
GitBranch  new-release
GitCommit  f861b9d9
GoArch     amd64
GoOS       darwin
```

**Comment by remyleone** [comment]
Hello, @t0k4rt we are working on this feature on the following pull request: https://github.com/scaleway/scaleway-cli/pull/1525 don't hesitate to test it out and give feedback :) It will ship in an upcoming release.
