### ISSUE TITLE
add --quiet option for scripting

### ISSUE THREAD

**Issue by matti** [scaleway/scaleway-cli#1584]
currently I need to figure out all the interactive things and disable them one by one:

```
scw init install-autocomplete=false send-telemetry=false secret-key=asdf
```

which will get broken when something interactive is added.

Please implement `--quiet` or similar which skips interactive prompts

**Comment by remyleone** [comment]
Hello @matti `scw init` is mostly designed for interactive setup. May I ask what is your use case for disabling those options? 
If you are looking for how to make a configuration file, feel free to check out the config file format available in the scaleway SDK: https://github.com/scaleway/scaleway-sdk-go/tree/master/scw or use environment variables for setting up the CLI.

**Comment by matti** [comment]
just that with envs it requires 3 variables, but with that it requires one :)

```
SCW_DEFAULT_ORGANIZATION_ID=asdfasdfsdf SCW_ACCESS_KEY=asdfasdfasdf SCW_SECRET_KEY=asdfasdfsdaf scw lb ip list
```

**Comment by jerome-quere** [comment]
Hello @matti you could also use
```
$> scw config set access-key=XXX secret-key=XXX default-organization-id=XXX 
$> scw lb ip list
```

As @remyleone explain the `init` comment is a the CLI onboarding command  and probably stay interactive for script usage you should rely on `config`  related command or env variables

**Comment by matti** [comment]
yea yea
