### ISSUE TITLE
`instance server list` doesn't list all servers

### ISSUE THREAD

**Issue by axelsimon** [scaleway/scaleway-cli#1589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted
`scw instance server list`

### Expected Behaviour
My servers should be shown.

Indeed, according to `scw instance server --help`, calling `list` should list *all* servers:
> scw instance server --help
> […]
> list          List all servers
> […]

### Actual Behaviour
No servers are shown, although i currently have two running servers:
The problem is servers that are not part of the default zone, or the default project, are not shown.

```
scw instance server list
ID   NAME  TYPE  STATE  ZONE  PUBLIC IP  PRIVATE IP  TAGS  IMAGE NAME  MODIFICATION DATE  CREATION DATE  VOLUMES  PROTECTED  SECURITY GROUP NAME  SECURITY GROUP ID  STATE DETAIL  ARCH  IMAGE ID
```

Extra flags, such as `zone=fr-par2` or `project=name-of-project` should be used to _filter_ the results, not to make them appear.

Or, at the very list, the help should be corrected to say:
> list          List servers in default zone and default project

## More info
Version    2.2.3+dev
BuildDate  unknown
GoVersion  go1.14.10
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       linux

Fedora 32

**Comment by taziden** [comment]
Same here.
If the current behavior is to be maintained, there should be a `--all` option to display all servers or something similar and documentation should be updated to clarify the current behavior.
