### ISSUE TITLE
Arm instances still mentioned in help and documentation

### ISSUE THREAD

**Issue by axelsimon** [scaleway/scaleway-cli#1591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

N/A

### Expected Behaviour

Arm instances shouldn't be mentioned, as they are not provided by Scaleway anymore.

### Actual Behaviour

Arm instances are mentioned:
- in the help of the CLI tool:
  ```
  * The **ARM** instances range is based on Cavium ThunderX SoCs and provides up to 64 Cores ARM 64bit, 128GB of RAM and 1TB SSD storage.
  Refer to the [ARM offer details](https://www.scaleway.com/en/arm-instances) for more information.
  ```  
  ([here](https://github.com/scaleway/scaleway-cli/blob/dae9a7a469a7dcc6398f53df4e584c74a53c6c88/internal/namespaces/instance/v1/instance_cli.go) and probably other places)
- in the documentation:
https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/instance.md

## More info
not needed

**Comment by Codelax** [comment]
Forwarded to instance team
