### ISSUE TITLE
Scaleway server documentation says PUT,  codebase uses PATCH

### ISSUE THREAD

**Issue by arianvp** [scaleway/scaleway-cli#164]
https://developer.scaleway.com/#servers-server-put  says  PATCH is not supported but PUT is,

but in the code, PATCH is used instead of PUT.  Why exactly is that?

https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/api.go#L927-L950

**Comment by moul** [comment]
I move the documentation on the dedicated repository: https://github.com/scaleway/api.scaleway.com/issues/5
