### ISSUE TITLE
Autocomplete not correctly installed

### ISSUE THREAD

**Issue by joan-prat** [scaleway/scaleway-cli#1654]
I tried to install the autocomplete with scw init (I downloaded the binary) on a Centos 8 Instance in your cloud but I am gettint the following error when I hit tab after scw (it is a symbolic link):

```
[root@xxxxxxxx ~]# scw -bash: _get_comp_words_by_ref: command not found
Strconv.Atoi: parsing "": invalid syntax
```

**Comment by Sh4d1** [comment]
👋 you need to install bash-completion 😄 
```bash
sudo yum -y install bash-completion
```

**Comment by joan-prat** [comment]
I see. It fixed the problem.

Thanks :+1:
