### ISSUE TITLE
Add support for security groups.

### ISSUE THREAD

**Issue by arianvp** [scaleway/scaleway-cli#168]
It would be nice to be able to configure security groups through the CLI

**Comment by moul** [comment]
Hi @arianvp, can give us an example of usage you would want to have ?

**Comment by arianvp** [comment]
Well for https://github.com/hex-sh/terraform-provider-scaleway   I'm using https://github.com/scaleway/scaleway-cli/tree/master/pkg/api to talk to the Scaleway API.  I want to declaratively describe my firewall  like you can do with AWS https://www.terraform.io/docs/providers/aws/r/security_group.html  but the current  API client of Scaleway has no functions for calling the security group resource.

So it's not really an addition to the scaleway-cli itself, but to the API that scaleway-cli uses.

**Comment by moul** [comment]
Ok, perfect, so we can add API helpers for now and decide how to include it in the cli, later

@QuentinPerez, this is for you :)

**Comment by arianvp** [comment]
#179 seems to fix this right?

**Comment by QuentinPerez** [comment]
Yes 😊 You can see examples here https://github.com/scaleway/scaleway-cli/pull/182
