### ISSUE TITLE
Missing Linux/Windows build for 2.2.4

### ISSUE THREAD

**Issue by decima** [scaleway/scaleway-cli#1704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted
```sh
sudo curl -o /usr/local/bin/scw -L "https://github.com/scaleway/scaleway-cli/releases/download/v2.2.4/scw-2.2.4-linux-x86_64"
```
> as described in the README

### Expected Behavior

Downloading the file

### Actual Behavior

Downloading an empty file

## More info

2.2.4 is missing linux/windows build, only Darwin version : https://github.com/scaleway/scaleway-cli/releases/tag/v2.2.4

**Work around**: getting 2.2.3 :rofl:

**Comment by remyleone** [comment]
The release was updated. Sorry for the inconvenience.
