### ISSUE TITLE
Two issues with Arm release (Illegal instruction"

### ISSUE THREAD

**Issue by RobSeder** [scaleway/scaleway-cli#172]
First, in the documentation on the main readme, the comments say to specify "arm" if you want to pull down the arm release. This needs to be "armhf".

```export ARCH=amd64  # can be 'i386', 'amd64' or 'arm'```
should be:
```export ARCH=amd64  # can be 'i386', 'amd64' or 'armhf'```

Second, once downloaded and installed (with no issues), no matter what arguments you call, "scw" returns one line "Illegal instruction" and that's it.

**Comment by moul** [comment]
Hi @RobSeder 

Can you give us the result of :  `uname -a` and `file /path/to/scw` ?

**Comment by RobSeder** [comment]
uname is:
````
Linux raspi05 4.1.6+ #810 PREEMPT Tue Aug 18 15:19:58 BST 2015 armv6l GNU/Linux
````
lsb_release is:
````
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
````
This is a Raspberry Pi 2. And scw is in: ````/usr/bin/scw````

**Comment by moul** [comment]
Ok, can you try with this link instead: https://github.com/scaleway/scaleway-cli/releases/download/v1.4.0/scw_1.4.0_linux_arm.tar.gz

This link is for **armv5** and should work aswell on **armv6** (raspberry pi) and **armv7**

```console
root@store:/tmp/scw_1.4.0_linux_arm# ./scw version
Client version: v1.4.0
Go version (client): go1.5
Git commit (client): 37b274939200e31381e1534f9ad19191279427e8
OS/Arch (client): linux/arm
root@store:/tmp/scw_1.4.0_linux_arm# file scw
scw: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
root@store:/tmp/scw_1.4.0_linux_arm#
```

I will update the build script to ensure **ARM** is build for **ARMv5** for extra compatibility

Can you tell me if my link works, if no, there is probably another bug and I will need to try on a raspberry pi

**Comment by RobSeder** [comment]
When doing the dpkg install:

    dpkg -i /tmp/scw.deb
I get this error:

    dpkg-deb: error: `/tmp/scw.deb' is not a debian format archive
    dpkg: error processing /tmp/scw.deb (--install):
     subprocess dpkg-deb --control returned error exit status 2
    Errors were encountered while processing: /tmp/scw.deb
and how it looks on the file system: 

    -rw-r--r--  1 root root 1943639 Aug 28 18:23 scw.deb

**Comment by moul** [comment]
I need to test on a Rasbperry PI, stay tuned

**Comment by RobSeder** [comment]
OK, thanks!

**Comment by moul** [comment]
Raspberry PI 2: **works**

```console
raspi2:/tmp # curl -L https://github.com/scaleway/scaleway-cli/releases/download/v1.4.0/scw_1.4.0_linux_arm.tar.gz > scw.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   403    0   403    0     0    683      0 --:--:-- --:--:-- --:--:--   685
100 1898k  100 1898k    0     0   655k      0  0:00:02  0:00:02 --:--:--  881k
raspi2:/tmp # tar xvzf scw.tgz
scw_1.4.0_linux_arm/scw
scw_1.4.0_linux_arm/README.md
scw_1.4.0_linux_arm/LICENSE.md
raspi2:/tmp # ./scw_1.4.0_linux_arm/scw version
Client version: v1.4.0
Go version (client): go1.5
Git commit (client): 37b274939200e31381e1534f9ad19191279427e8
OS/Arch (client): linux/arm
SalonPlex:/tmp # uname -a
Linux SalonPlex 3.19.3 #1 SMP Sun Apr 5 11:16:13 2015 armv7l GNU/Linux
raspi2:/tmp #
```

Now testing on older Raspberry PI

**Comment by RobSeder** [comment]
@moul first, my mistake, I didn't even read the URL - I thought that was a direct replacement for the .deb download - so I was naming the output file as .deb.

So - realizing that, I download, and unzip that .gz file - but when I run that ./scw, I still do get "Illegal instruction"

Note, I just realized this is a Raspberry Pi B (the older version, not an latest one) - I was connecting to the wrong device. Let me try on (the more relevant) Raspberry Pi 2.

**Comment by moul** [comment]
Ok no problem, but I think there is really a bug on older Raspberry Pi, so I will try to fix it :)

**Comment by RobSeder** [comment]
By the way, I yes - I confirmed, that .gz file works on Raspberry Pi 2 and a Banana Pi Pro too (similar architecture, also ARM-based). 

So, I think the only actual problem is the typo in the main readme. Changing from "arm" to "armhf" allows the download to proceed and that package DOES work on the RPI2 and the BanPi Pro too. Thanks and sorry for the earlier confusion!
