### ISSUE TITLE
Missing documentation for `apple-silicon` subcommand

### ISSUE THREAD

**Issue by marco-m** [scaleway/scaleway-cli#1837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## The problem

Hello,
the latest version of scw (v2.3.0) added the `apple-silicon` subcommand (yeah!), but:
- directory scaleway-cli/master/docs/commands is missing its related documentation
- file scaleway-cli/README, section "Reference Documentation, is missing its related documentation

**Comment by remyleone** [comment]
Hello @marco-m sorry, it is not included in the CI pipeline at the moment. I will add it :) In the meantime you can generate it yourself using:
`go run ./cmd/scw-doc-gen/`

**Comment by marco-m** [comment]
merci @remyleone :-)
