### ISSUE TITLE
dns subcommand is missing

### ISSUE THREAD

**Issue by maelvls** [scaleway/scaleway-cli#1876]
I use the DNS service offered by Scaleway. Unlike other services like "instances", the CLI does not seem to be capable of managing DNS records.

Is there a plan to have the subcommand `dns` at some point? E.g.:

```sh
scw dns
```

Thank you!

**Comment by Sh4d1** [comment]
Hey! I'll see what can be done 😄

**Comment by maelvls** [comment]
Woah, that was quick!!! Thank you!!

![scz-dns](https://user-images.githubusercontent.com/2195781/115008565-8c936c00-9eab-11eb-9285-dd53743404e7.png)

**Comment by remyleone** [comment]
@maelvls Glad you like it :) Don't hesitate to give us feedback using `scw feedback` :)
