### ISSUE TITLE
Docker latest tag is outdated

### ISSUE THREAD

**Issue by antonindupontsinch** [scaleway/scaleway-cli#1888]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

```
$ docker run -it --rm scaleway/cli:latest version           

Client version: v1.20
Go version (client): go1.13
Git commit (client): 
OS/Arch (client): linux/386
```

### Expected Behavior

I expect to have the latest version.

### Actual Behavior

I get a two years old outdated version.

## More info

- https://hub.docker.com/r/scaleway/cli/tags?page=1&ordering=last_updated&name=latest

**Comment by remyleone** [comment]
It is now fixed :) Keep in mind you can check for a particular version by using a version for instance:


`docker run -it --rm scaleway/cli:v2.3.0 version`
