### ISSUE TITLE
Invalid JSON on update

### ISSUE THREAD

**Issue by guyguy333** [scaleway/scaleway-cli#1933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw rdb instance list --output=json`

### Expected Behavior

A valid JSON output even if there is a new CLI version available

### Actual Behavior

[...](VALID JSON)
a new version of scw is available (2.3.1), beware that you are currently running 2.3.0

new version message breaks JSON parsing.

## More info

Run a command with version 2.3.0 to reproduce

**Comment by remyleone** [comment]
#1478

**Comment by Monitob** [comment]
Done on #2513

**Comment by Codelax** [comment]
This is not enough, the broken behavior is not tested
