### ISSUE TITLE
Study whether or not we can use autocomplete from cobra 1.2

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#1946]
https://github.com/scaleway/scaleway-cli/pull/1945 upgrades to cobra 1.2. We can maybe use autocomplete features from this release. We should study whether or not it would be a good fit for the CLI

Reference: <https://github.com/spf13/cobra/blob/main/shell_completions.md>

**Comment by Codelax** [comment]
Cobra does not use the same system of arguments
`scw instance create type=DEV1-S image=ubuntu_jammy`
It does not fit our usage and completion would provide less
