### ISSUE TITLE
cli allows creating containers with invalid name

### ISSUE THREAD

**Issue by lalyos** [scaleway/scaleway-cli#2064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw container container create name=not-god-name namespace-id=$NS_ID`

### Expected Behavior

The sameerrormessage should be displayed as the console:
> Container name must only contain lowercase alphanumeric characters.

### Actual Behavior

The container gets created.

**Comment by remyleone** [comment]
Hello, it seems that this bug is now corrected in the console. Do not hesitate to open a new ticket in case you have another question.

**Comment by Codelax** [comment]
This is wrong validation on console's side, cli enforce api rules.
