### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2124]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Here's a fix that can be done I guess, for the CLI's documentation about kubelet's additional settings : https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/k8s.md#update-a-pool-in-a-cluster
In the table it should be : kubelet-args.{key} instead of kubelet-args.value.{key}
Issue spotted here : https://scaleway-community.slack.com/archives/CD9JPK4KF/p1644845477576589

## Command attempted

```
scw k8s pool update <pool-id> kubelet-args.value.containerLogMaxSize=20Mi
Cannot unmarshal arg 'kubelet-args.value.containerLogMaxSize=20Mi': cannot set nested field for unmarshalable type string
```

**Comment by Codelax** [comment]
Fixed in #2518
