### ISSUE TITLE
Kubeconfig generated with wrong permissions

### ISSUE THREAD

**Issue by aimbot31** [scaleway/scaleway-cli#2211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw k8s kubeconfig install <cluster-id>`

### Expected Behavior

The command should creates a new kubeconfig file if none exist.
The generated kubeconfig should be only writable and readable by the owner (600 rw--) in order to avoid security issues.

### Actual Behavior

The command creates a new kubeconfig file if none exists with these permissions 644 (rw-r-r).

## More info

N/A

**Comment by remyleone** [comment]
It is strange because in the code it is the right permission that seems to appear: https://github.com/scaleway/scaleway-cli/blob/c7a3d57d6675188665369990284bbcde696586e8/internal/namespaces/k8s/v1/custom_kubeconfig_helpers.go#L62

**Comment by remyleone** [comment]
Thanks a lot for the feedback :) It is now fixed.
