### ISSUE TITLE
Implement a 'scw baremetal server-type list'

### ISSUE THREAD

**Issue by jean-christophe-manciot** [scaleway/scaleway-cli#2222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This command would be the equivalent of ```scw instance server-type list``` for baremetal servers. 

### How I imagine scw could expose this functionality

List all baremetal server-types in the default zone
```
scw baremetal server-type list
```
List all baremetal server-types in fr-par-3 zone
```
scw baremetal server-type list zone=fr-par-3
```

**Comment by remyleone** [comment]
It is now supported on the master branch and will be available in the next release :)
