### ISSUE TITLE
2.5.0 and 2.5.1: line 1: Not: command not found

### ISSUE THREAD

**Issue by jean-christophe-manciot** [scaleway/scaleway-cli#2241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted
All commands fail with 2.5.1 and 2.5.0. 

### Expected Behavior
No such issue with 2.4.0:
```
# scw instance server-type list --profile <profile_name>
NAME         HOURLY PRICE  LOCAL VOLUME SIZE  CPU  GPU  RAM      ARCH    AVAILABILITY
DEV1-S       € 0.01        0 B                2    -    2.0 GiB  x86_64  available
DEV1-M       € 0.02        0 B                3    -    4.0 GiB  x86_64  available
DEV1-L       € 0.04        0 B                4    -    8.0 GiB  x86_64  available
DEV1-XL      € 0.06        0 B                4    -    12 GiB   x86_64  available
GP1-XS       € 0.084       0 B                4    -    16 GiB   x86_64  available
GP1-VIZ      € 0.10        0 B                8    -    32 GiB   x86_64  available
GP1-S        € 0.17        0 B                8    -    32 GiB   x86_64  available
GP1-M        € 0.34        0 B                16   -    64 GiB   x86_64  available
GP1-L        € 0.66        0 B                32   -    128 GiB  x86_64  available
GP1-XL       € 1.40        0 B                48   -    256 GiB  x86_64  available
RENDER-S     € 1.00        0 B                10   1    45 GiB   x86_64  available
STARDUST1-S  € 0.002       0 B                1    -    1.0 GiB  x86_64  out of stock
```

### Actual Behavior
For instance:
```
# scw instance server-type list --profile <profile_name>
/usr/local/bin/scw: line 1: Not: command not found
```

## More info
```
# scw version
/usr/local/bin/scw: line 1: Not: command not found
```
Ubuntu impish 21.10

**Comment by remyleone** [comment]
I cannot reproduce your issue. How do you install scw? Have your tried using the binary version available on https://github.com/scaleway/scaleway-cli/releases/tag/v2.5.1 ?

**Comment by jean-christophe-manciot** [comment]
It seems that the URL has been changed.

**Comment by toniopelo** [comment]
@remyleone The problem here is that you changed the naming convention for your binaries.
Since `2.5.1` `scw-$VERSION-linux-x86_64` was turned into `scaleway-cli_$VERSION_linux_amd64`.
If this change is supposed to be the new standard, then I made this PR for you to update the readme quickly : https://github.com/scaleway/scaleway-cli/pull/2270
