### ISSUE TITLE
Error on Go get

### ISSUE THREAD

**Issue by meyskens** [scaleway/scaleway-cli#230]
When getting the dependencies for the api in Go I get the following error:

```
# github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client
/usr/src/spouse/src/github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client/gotty-client.go:247: undefined: signal.Reset
```

Any idea what it may be?

**Comment by QuentinPerez** [comment]
Hi @meyskens 

`signal.Reset` has been introduced with [go1.5](https://golang.org/doc/go1.5)
`The os/signal package adds new Ignore and Reset functions.`
Please update your go version, we will try to add a warning, thanks :+1:

**Comment by meyskens** [comment]
Thanks :D I'm not that into Go
