### ISSUE TITLE
scaleway-cli is missing from AUR

### ISSUE THREAD

**Issue by Kukkerem** [scaleway/scaleway-cli#2318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`yay -S scaleway-cli`

### Expected Behavior

Download and install the package.

### Actual Behavior

```
 -> Could not find all required packages:
        scaleway-cli (Target)
```

## More info

Package is not in AUR:
https://aur.archlinux.org/packages/scaleway-cli -> 404 - Page Not Found

**Comment by seblu** [comment]
Hello,

It's in [community] now.

https://archlinux.org/packages/community/x86_64/scaleway-cli/

**Comment by Kukkerem** [comment]
Hello,

In this case, it's a documentation issue. :)

Thanks for the link!
