### ISSUE TITLE
cmd_cp gateway

### ISSUE THREAD

**Issue by FLYBYME** [scaleway/scaleway-cli#234]
What is the gatway url or ip?

**Comment by moul** [comment]
the gateway parameter is the name of one of your servers with a public IP address

- server1 with public ip address
- server2 without public ip address
- server3 without public ip address

```console
$ scw cp server1....
$ scw cp --gateway=server1 server2....
$ scw cp --gateway=server1 server3....
```

You can also setup the `SCW_GATEWAY` variable

```console
$ export SCW_GATEWAY=server1
$ scw cp server1...
$ scw cp server2...
$ scw cp server3...
```

**Comment by moul** [comment]
I'm closing this issue because it has been inactive for a few weeks.

Please reopen if you still encounter this issue.

Thank you!
