### ISSUE TITLE
Fix scw version

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

```
$ scw version
Version    2.0.0-dev
BuildDate  unknown
GoVersion  go1.18
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin
```

### Expected Behavior

I expect to see the correct version in this command

### Actual Behavior

I only see a default version that is incorrect

**Comment by Codelax** [comment]
PR made to add version https://github.com/Homebrew/homebrew-core/pull/103142

**Comment by remyleone** [comment]
Now fixed, in case you have it installed with homebrew just do a `brew reinstall scw`
