### ISSUE TITLE
Docker image reports wrong scw version

### ISSUE THREAD

**Issue by ohemelaar** [scaleway/scaleway-cli#2343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted
```bash
docker run --rm -it scaleway/cli:v2.5.1 version
```

> Version    2.0.0-dev
BuildDate  2022-04-04T04:48:15PM
GoVersion  go1.15.15
GitBranch  HEAD
GitCommit  915ea90e
GoArch     amd64
GoOS       linux
a new version of scw is available (2.4.0), beware that you are currently running 2.0.0-dev

### Expected Behavior

The version number shown should be 2.5.1.

### Actual Behavior

The version number is 2.0.0-dev.

## More info

I checked the `915ea90e` commit and it matches the 2.5.1 tag from Apr 4 18:41:55 2022, so my understanding is that the scw CLI is up to date but indicates an outdated version.

**Comment by Codelax** [comment]
Hi thank you for reporting this, it should be fixed in future releases. #2341
