### ISSUE TITLE
Creating an instance with a correct project-id fails with: error while creating your public IP

### ISSUE THREAD

**Issue by jean-christophe-manciot** [scaleway/scaleway-cli#2422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted
```
scw --output json instance server create --profile my_profile --wait boot-type="local" image="ubuntu_jammy" ip="new" ipv6="true" name="ubuntu_jammy:fr-par-2" organization-id="45247b03-7f11-4908-9dc5-94c6d2b0659f" project-id="45247b03-7f11-4908-9dc5-94c6d2b0659f" root-volume="local:30GB" stopped="false" tags.0="scw-fr-par-2-GP1-M" type="GP1-M" zone="fr-par-2"
```

### Expected Behavior
Instance created

### Actual Behavior
```
{"error":"error while creating your public IP: scaleway-sdk-go: invalid argument(s):  does not respect constraint, Must contain one of ['organization', 'project']"}
```

## More info
```
Ubuntu 22.04
Version    2.5.4
BuildDate  2022-07-04T14:22:15Z
GoVersion  go1.17.11
GitBranch  HEAD
GitCommit  95f1c19e
GoArch     amd64
GoOS       linux
```

The instance is correctly created when the project ID is not mentioned (using the same other parameters) .

**Comment by remyleone** [comment]
Could you try with only project_id specified?

**Comment by Codelax** [comment]
As specified in the error message, instance creation request must contain only one of organization or project.
You should remove `organization-id="45247b03-7f11-4908-9dc5-94c6d2b0659f"` when adding `project-id="45247b03-7f11-4908-9dc5-94c6d2b0659f"`

**Comment by jean-christophe-manciot** [comment]
@Codelax 
Then all the documentation must be updated to specify that it's one or the other, for instance [here](https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/instance.md#create-server).

**Comment by Codelax** [comment]
It comes from two problems, I created issues to track this, #2579 #2578
