### ISSUE TITLE
Docs: missing information on node_type

### ISSUE THREAD

**Issue by aichbauer** [scaleway/scaleway-cli#2429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the [docs on how to add a pool](https://www.scaleway.com/en/docs/compute/kubernetes/api-cli/creating-managing-kubernetes-lifecycle-cliv2/#adding-a-pool-to-a-k8s-cluster) links to this [document](https://github.com/scaleway/scaleway-cli/blob/master/docs/commands/k8s.md#kapsule-pool-management-commands) if we want additional information.

Although this document states that the default value is `DEV1-M`, it does not state that this is the minimum instance type to choose. So I would add additional information for that in the table by changing:

`The node type is the type of Scaleway Instance wanted for the pool`

to

`The node type is the type of Scaleway Instance wanted for the pool (minimum DEV1-M)`

### Questions

* What value does this feature bring to end users? --> Users who are testing scaleway would save time because for testing the tools most of the time users choose the smallest possible instances types
* How urgent is the need (nice to have feature or need to have)? --> not urgent, but this could def. help to decrease support tickets or unnecessary chats with the support team

**Comment by Codelax** [comment]
Hi, this is generated from kapsule documentation, I gave this issue to kapsule team.

**Comment by louisportay** [comment]
looking at it

**Comment by louisportay** [comment]
Scaleway docs are [being updated](https://github.com/scaleway/docs-content/pull/769)
[Developer Docs](https://developers.scaleway.com/en/products/k8s/api/) will reflect the change fairly soon as well

Thanks!
