### ISSUE TITLE
--config flag not working

### ISSUE THREAD

**Issue by Codelax** [scaleway/scaleway-cli#2451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

 `scw --config /tmp/config.yaml instance server list`

### Expected Behavior

Fail as the config used have an invalid secret_key

### Actual Behavior

CLI still load default config instead of specified file and run correctly

## More info

`scw --config /tmp/config.yaml info` works as intended

**Comment by Monitob** [comment]
Please add the flag `-c` on top of this priority 
```
 50 // GetConfigPath returns the default path.
 51 // Default path is based on the following priority order:
 52 // - $SCW_CONFIG_PATH
 53 // - $XDG_CONFIG_HOME/scw/config.yaml
 54 // - $HOME/.config/scw/config.yaml
 55 // - $USERPROFILE/.config/scw/config.yaml
```
