### ISSUE TITLE
Enable Protected Kubernetes Cluster

### ISSUE THREAD

**Issue by codezart** [scaleway/scaleway-cli#2463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently on scaleway, the instances are protected from Deletion if the `Activate protected Instance` is checked.
It would be preferable if the kubernetes cluster also had the functionality to protect the instance from being deleted.

**Comment by Codelax** [comment]
Hi, thanks for your feedback, this is a missing feature in kapsule product, you can ask for features on scaleway's [feature request page](https://feature-request.scaleway.com/).
If you have an issue with scaleway's cli I will be glad to help you.
