### ISSUE TITLE
RDB: list init_settings and settings

### ISSUE THREAD

**Issue by Monitob** [scaleway/scaleway-cli#2547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be available to list the `settings` and `init_settings` from an rdb instance.

### How I imagine scw could expose this functionality

e.g. `scw rdb engine <engine-type> settings list`
e.g `scw rdb engine <engine-type> init_settings list`

The information is available on the endpoint `api.scaleway.com/rdb/v1/regions/fr-par/database-engines`

I couldn't find information on the doc but present in the [SDK-GO](https://github.com/scaleway/scaleway-sdk-go/blob/master/api/rdb/v1/rdb_sdk.go#L1033)

**Comment by remyleone** [comment]
Init settings and settings are already given by the list of engines. Basically if they are HOT CONFIGURABLE it means that they can be changed without forcing to create a new instance.

**Comment by Monitob** [comment]
We confirm that the settings and init_settings are not listed. Here the current [PR](https://github.com/scaleway/scaleway-cli/pull/2548) to add the settins
