### ISSUE TITLE
Snapshot creation from S3 bucket ask for volume id

### ISSUE THREAD

**Issue by n-Arno** [scaleway/scaleway-cli#2556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw instance snapshot create zone=fr-par-1 name=my-image volume-type=unified bucket=my-bucket key=image.qcow2`

### Expected Behavior

The import of the qcow2 image start.

### Actual Behavior

The cli fails (error below), asking for a mandatory volume id (which is not needed in this use case).

`scaleway-sdk-go: field VolumeID cannot be empty in request`

## More info

```
$ scw version
Version    2.6.0
BuildDate  unknown
GoVersion  go1.19.1
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin
```

=> MacOS Big Sur 11.7

=> steps to reproduce: execute command from help `scw instance snapshot create --help`

```
  Import a QCOW file as an instance snapshot
    scw instance snapshot create zone=fr-par-1 name=my-imported-snapshot volume-type=unified bucket=my-bucket key=my-qcow2-file-name

$ scw instance snapshot create zone=fr-par-1 name=my-imported-snapshot volume-type=unified bucket=my-bucket key=my-qcow2-file-name
scaleway-sdk-go: field VolumeID cannot be empty in request
```

**Comment by remyleone** [comment]
Already fixed in master. Will be available in the next release
