### ISSUE TITLE
cannot connect VM Port 22

### ISSUE THREAD

**Issue by avenbreaks** [scaleway/scaleway-cli#2576]
Hello, scaleway VM Cannot connect to SSH port 22, inboud open port 22 

![image](https://user-images.githubusercontent.com/93043826/200706075-bb710cac-37ca-4aee-b386-b692b60b8dc1.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by remyleone** [comment]
Hello, this is not a problem related to the CLI. I suggest checking your security groups, trying to boot on rescue mode, and opening a support ticket in case you cannot connect to your instance.
