### ISSUE TITLE
Manage databases via CLI

### ISSUE THREAD

**Issue by NextBasket-Petyo** [scaleway/scaleway-cli#2637]
## Description

We would like to be able to send commands/configurations/backups/snapshots of the managed SQL databases.

## How this functionality would be exposed

Separate command for managed database

## Version

Version    2.6.1
BuildDate  unknown
GoVersion  go1.19.2
GitBranch  unknown
GitCommit  unknown
GoArch     arm64
GoOS       darwin

**Comment by remyleone** [comment]
Hello, Have you explored the `scw rdb` commands? what is currently not working for you with them?

**Comment by NextBasket-Petyo** [comment]
Yep, that works, sorry for not doing more before posting. My bad. Have a nice day.
