### ISSUE TITLE
SCW keeps using my CPU

### ISSUE THREAD

**Issue by zlx021120** [scaleway/scaleway-cli#2692]
## Command attempted
```bash
sudo curl -o /usr/local/bin/scw -L https://github.com/scaleway/scaleway-cli/releases/download/v2.7.0/scaleway-cli_2.7.0_linux_amd64

sudo chmod +x /usr/local/bin/scw

scw init
#I fill my info

scw instance server create type=STARDUST1-S zone=fr-par-1 image=debian_bullseye root-volume=l:10G name=FR ip=none ipv6=true project-id=f09e5860-eb42-4784-8c98-*********
```

### Actual Behavior

I succeeded create the instance

## More info

**But it keeps using my CPU, I think it likes a mining virus
when I run "ps -ef" to get the pid of scw and run "kill -9 pid",linux shows "bash: kill: (16490) - No such process".The reason is its pid changed very frequently,so what should I do?**

![ ](https://i2.100024.xyz/2022/12/26/lq09gv.webp)

![ ](https://i2.100024.xyz/2022/12/26/lqgjqs.webp)

**Comment by zlx021120** [comment]
I can give you my-linux-root'passwd if you need.
Thanks for your help!

**Comment by Codelax** [comment]
Thanks for reporting, there may be issues with autocomplete, I'll look into it

**Comment by remyleone** [comment]
This autocomplete function is useful for completing the command while you type in bash. Are you using bash as your shell? Do you still have this behavior if you use a different shell? (Zsh or fish for instance)

**Comment by Codelax** [comment]
The running process in the background is scw with `autocomplete script shell=bash`, this is the command used to generate the bash script to do autocomplete.
This is the command that should be used in your .bashrc as `eval $(scw autocomplete script shell=bash)` to generate and load the autocomplete script each time your bash startup.
The autocomplete script can also be set in bash completions folder, the scripts should be in `/usr/share/bash-completion/completions/`. You can add it by doing `scw autocomplete script shell=bash > /usr/share/bash-completion/completions/scw`

If you are using the `eval` command in your bash config, please make sure this config is not loaded repeatedly, this should be the issue, as generating the autocomplete script is fast but resource consuming.

**Comment by zlx021120** [comment]
I'm sorry I don't understand the bash command，and I didnt know the autocomplete.
My requirement is that I can use scw to create instances normally (this function is normal), but after using it I can close it or make it not consume a loy of CPU
Is it possible to do that? And what commands do I need to execute?
Thanks for your help,sir.

**Comment by Codelax** [comment]
When using `scw init`, if you accept to install autocomplete, it will add a line to your bash config.

In `~/.bashrc` (on linux), you should have one line with `eval $(scw autocomplete script shell=bash)`, you can try removing it to see if the problem persist. It will remove your completion for `scw` commands.
If this fix the issue, it means you have another issue with your config being loaded repeatedly.

**Comment by zlx021120** [comment]
###When using , if you accept to install autocomplete, it will add a line to your bash config.
Sorry,I didnt know what is "accept to install autocomplete",I install scw by running
 ```
curl -o /usr/local/bin/scw -L https://github.com/scaleway/scaleway-cli/releases/download/v2.7.0/scaleway-cli_2.7.0_linux_amd64
```

But it show this in the /root/.bashrc
```
root@linux:~# cat /root/.bashrc
# Scaleway CLI autocomplete initialization.
eval "$(scw autocomplete script shell=bash)"
```

So,what should I do to prevent the scw using too much CPU?

**Comment by zlx021120** [comment]
###you should have one line with , you can try removing it
Can you tell me what should be removed?
```scw init``` or ```eval $(scw autocomplete script shell=bash)```

And I didnt know where is the ```scw init```

**Comment by Codelax** [comment]
You can try commenting the eval line in `~/.bashrc` to disable autocomplete and see if it fix your issue.
```
# Scaleway CLI autocomplete initialization.
#eval "$(scw autocomplete script shell=bash)"
```

The `eval "$(scw autocomplete script shell=bash)"` line will generate an autocomplete script and load it in bash when you start your shell.
As you have seen in your process list, this command is run a lot, this is what consume too much CPU.
This means that bash is run with his config a lot of time, this is probably another issue on your end that you should look into.

**Comment by zlx021120** [comment]
oh,it have been solved.
Thanks for your explanation and the solution. 👍
