### ISSUE TITLE
Bad `scw run` documentation

### ISSUE THREAD

**Issue by brmzkw** [scaleway/scaleway-cli#272]
`scw help run` shows the following example:

`$ scw run --bootscript=3.2.34 --env="boot=live rescue_image=http://j.mp/scaleway-ubuntu-trusty-tarball" 50GB bash`

That's wrong, you need to add `-v=50GB`.

`$ scw run --bootscript=3.2.34 --env="boot=live rescue_image=http://j.mp/scaleway-ubuntu-trusty-tarball" -v=50GB bash`

**Comment by brmzkw** [comment]
As seen with @QuentinPerez , the command is actually valid and does what's "expected" (ie. it creates a 50GB rescue volume) but the documentation feels unclear.

**Comment by moul** [comment]
Ok
