### ISSUE TITLE
Chocolatey package not updated

### ISSUE THREAD

**Issue by pondichys** [scaleway/scaleway-cli#2726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

Greetings,
I installed the scaleway cli using chocolatey on my Windows workstation and it is not updated since 27-08-2022

![image](https://user-images.githubusercontent.com/17532580/213630830-a1553405-69b5-4372-a20e-7d1ae76b518f.png)

### Expected Behavior

The package should be updated to the latest release available.

### Actual Behavior

Current chocolatey package still at version 2.5.6

Can you have a look at this please?
Thank you.

**Comment by remyleone** [comment]
This might be relevant: https://www.dolthub.com/blog/2021-10-13-how-to-publish-winget-chocolatey-packages-with-github-actions/

**Comment by pondichys** [comment]
Thanks a lot for your help! Much appreciated.
