### ISSUE TITLE
Using ALL as a default_region didn't work 

### ISSUE THREAD

**Issue by jbriard** [scaleway/scaleway-cli#2739]
## Description:
I would like to get all (from any region and AZ) the resources I have using with a single request.
When using `default_region: all` in the configuration file the CLI return an error.

## How to reproduce:
Modifies` .config/scw/config.yaml`
use default_region: all
and run any command

### Command attempted
`scw instance security-group list`
It's the same for all the tested resources.

### Expected Behavior
I can get the List of all the securities groups (or any resources asked)

### Actual Behavior
`scaleway-sdk-go: invalid default region format 'all', available regions are: fr-par, nl-ams, pl-waw`

## More info
If I let the conf file with a valid region and use the zone argument `zone=all`, I can get the attended information.

## Version

Version    2.10.0
BuildDate  unknown
GoVersion  go1.19.5
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       linux

**Comment by Codelax** [comment]
This feature is not expected.
`all` region is invalid for a lot of commands like `scw container namespace create`
The only commands that can use the `all` locality are listing commands
