### ISSUE TITLE
No way to empty tags list

### ISSUE THREAD

**Issue by chazer** [scaleway/scaleway-cli#2750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

```
$ scw instance server update $server_id tags.0=T tags.1=Q | grep 'Server\.Tags'
Server.Tags.0                      T
Server.Tags.1                      Q

$ scw instance server update $server_id tags.0=T | grep 'Server\.Tags'
Server.Tags.0                      T

$ scw instance server update $server_id tags=none | grep 'Server\.Tags'
Server.Tags.0                      T

$ scw instance server update $server_id tags= | grep 'Server\.Tags'
Cannot unmarshal arg 'tags': missing index on the array
```

### Expected Behavior

Tags list should be empty after set to 'none'

### Actual Behavior

First entry in the tags list is always kept.
No effects on set tags to 'none'

## More info

```
$ scw version
Version    2.10.0
BuildDate  2023-01-24T14:03:42Z
GoVersion  go1.19.5
GitBranch  HEAD
GitCommit  d4d72f6c
GoArch     amd64
GoOS       darwin
```

**Comment by Codelax** [comment]
Hi, thank you for reporting this.
You can remove tags by using `none`.
Example: `scw instance server update <uuid> tags=none`
There is an issue with our documention, I'll look to fix it
