### ISSUE TITLE
download a rdb backup locally 

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Mia-Cross** [comment]
The command already exists:
```
$ scw rdb backup download be103088-deba-4123-a89b-87e3a62cb932 
Exporting backup... OK
Backup downloaded to be103088-deba-4123-a89b-87e3a62cb932.custom successfully (1.3 kB written)
```
