### ISSUE TITLE
add a visualization of all servers in a placement group for the get placement group

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Codelax** [comment]
Placement Group already list servers
```
 ± scw instance placement-group get 6b55e706-5fc3-4e4d-a323-a786b64bf71d           
Placement Group:
ID               6b55e706-5fc3-4e4d-a323-a786b64bf71d
Name             cli-pg-strange-dhawan
Organization     ee7bd9e1-9cbd-4724-b2f4-19e50f3cf38b
Project          ee7bd9e1-9cbd-4724-b2f4-19e50f3cf38b
PolicyMode       optional
PolicyType       max_availability
PolicyRespected  true
Zone             fr-par-1

Servers:
ID                                    NAME                      POLICY RESPECTED
223fddbd-2627-49e5-acc2-2df834195e12  cli-srv-romantic-villani  true
```
