### ISSUE TITLE
Can't create a server without public address

### ISSUE THREAD

**Issue by ElNounch** [scaleway/scaleway-cli#285]
If `--ip-address` option not specified or is an empty string, a dynamic public IP is assigned to the server.

I explored :
- Adding a `--no-dynamic-ip` command line flag #284
- Handling IPs named "no" or "none" #283

**Comment by moul** [comment]
Hi @ElNounch, thank you for your PRs,

For now there is an easy (but badly documented way) to do this, you need to set a gateway, i.e:

* `scw run --name=my-gateway ubuntu`, wait for the server to be available through SSH
* `scw run --gateway=my-gateway --name=my-server-without-public-ip-address ubuntu` -> will create a server without public ip address
* `SCW_GATEWAY=my-gateway scw run --name=... ubuntu` -> same as above
* `SCW_GATEWAY=my-gateway scw exec my-server-without-public-ip-address` -> connect ** my-server-without-public-ip-address** using **my-gateway**

I like much more your solutions in #283 + #284

**Comment by ElNounch** [comment]
If we agree #283 is the way to go, might as well close #284.

**Comment by QuentinPerez** [comment]
#283 merged thank you @ElNounch :smiley:
