### ISSUE TITLE
container: add support for a deploy function

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2855]
This command will reuse buildpack to build locally a container image, push it to a dedicated namespace and then deploy the container.

**Comment by Codelax** [comment]
This is an idea of flow for this command.
This takes into account that we do not have our own config format, it could be considered.
We can also consider an interactive survey to ask user for missing informations and maybe init a config with this informations.

### Project scanning part:
- Search for `./Dockerfile`
- Search for buildpack's `project.toml`
- Check docker daemon availability

We need to define a priority order if both dockerfile and buildpack's config are present.

### Variables
We need a couple of variables, they can be specified in the cli command or will be fetched from local config.
- `project_name`
- `listen_port`
- `buildpack_image`: defaults to paketo full or base builder

## Dockerfile

### Variables
- `project_name`: local folder name
-  `listen_port`: defaults ot 80 or from Dockerfile with `EXPORT` directive

Steps:
- Build
- Push
- Create and deploy container

## Buildpack

### Variables
- `project_name`: local folder name or [project's descriptor](https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md)
- `listen_port`: defaults to 80 or should we ask the user ?
- `buildpack_image`: get from `project.toml` or maybe we can let pack find it

### Steps

- Build using [pack](https://github.com/buildpacks/pack)
- Push
- Create and deploy container
