### ISSUE TITLE
no autocomplete available for mnq get/delete/update credentials

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#2897]
```
$ scw mnq credential get
         --       region=
```

Here I should find a list of the credentials that exist in a given zone. If several namespace are available I should have a paginated example with a set of credentials in all the namespace.

**Comment by Codelax** [comment]
`namespace-id` is required for `credential list`.
When doing `scw mnq credential get <tab>`, there is no `namespace-id`.
It makes it impossible to list credentials for completions, current arguments completion would work otherwise

**Comment by jremy42** [comment]
I've managed to add some of the autocompletions for:

-`scw mnq nats get-account`
-`scw mnq nats list-credentials`
-`scw mnq sqs list-credentials`
-`scw mnq sqs get-credentials`
-`scw mnq sns list-credentials`
-`scw mnq sns get-credentials`

However, for the NATS accounts, I agree with @Codelax that it would result in too many requests. I'm closing the ticket and will open a new one if it becomes necessary to do so for NATS.

#3700
