### ISSUE TITLE
Typo at the "Pricing" page in your main website

### ISSUE THREAD

**Issue by tark-hidden** [scaleway/scaleway-cli#297]
I have no idea where I can report about typo at your [website page](https://www.scaleway.com/pricing/) without f##ng registration. I haven't account in Twitter, Instagram and other asocial networks.

First block with low-price tariff has title "50GBM SSD Disk". GBM?..

**Comment by QuentinPerez** [comment]
Thank you @vikbez

**Comment by vikbez** [comment]
Fixed in repository, will be fixed publicly on next release !
