### ISSUE TITLE
Make install config resilient in case a product is missing on a given zone

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#3270]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

```
scw instance ssh install-config zone=fr-par-2
```

**Comment by Codelax** [comment]
When using `fr-par-2`, it will indeed use it but will fail as apple-silicon is not available.
Will have to wait for https://github.com/scaleway/scaleway-sdk-go/pull/1692 to detect when service is not available for given locality.
