### ISSUE TITLE
loadbalancer subscriber creation panic

### ISSUE THREAD

**Issue by Monitob** [scaleway/scaleway-cli#3294]
## How to reproduce:
```scw lb subscriber create name="test-dev"```
## Version

Version    2.18.0
BuildDate  unknown
GoVersion  go1.20.6
GitBranch  unknown
GitCommit  unknown
GoArch     amd64
GoOS       darwin

**Comment by yfodil** [comment]
fixed by https://github.com/scaleway/scaleway-cli/pull/3296
