### ISSUE TITLE
IPv6 fields

### ISSUE THREAD

**Issue by ewoutp** [scaleway/scaleway-cli#334]
Please add the IPv6 related fields to the server definitions (in the api package).

**Comment by moul** [comment]
Fixed with #335, not yet released, but you can build the latest version by yourself

**Comment by ewoutp** [comment]
This solves only one side of it. The creation of servers.
I also need to read the IPv6 address in a "get-server" or "list-servers" action.

**Comment by QuentinPerez** [comment]
Hi @ewoutp, the PR #339 solves your needs ?

**Comment by ewoutp** [comment]
Yes, looks good. thx
