### ISSUE TITLE
CMD scw exec points to two images/server

### ISSUE THREAD

**Issue by pascalandy** [scaleway/scaleway-cli#358]
~|⇒ scw ps

a4a9dbb3            9 minutes           running             444.33.111.222      sun                     VC1S

`~|⇒ scw exec sun`
- b63737fd          server:sun          sun                 x86_64
- a4a9dbb3          server:sun          sun                 x86_64
FATA[0000] cannot execute 'exec': Too many candidates for sun (2)

I'm trying to delete b63737fd via scw rmi or scw rm, the system does not allow to do it. 

How can I clean this? 

Thank you!

**Comment by QuentinPerez** [comment]
Hi @pascalandy,

Can you flush the cache with `scw _flush-cache` and retry ?

**Comment by pascalandy** [comment]
I did `scw _flush-cache`.
scw version v1.9.0, build 582b7eabd2489b81cf3c3a71e6268bdd033080e3

Meanwhile, I deleted most of the servers I was working on. So let's close this for now and let's work on this https://github.com/scaleway/docker-machine-driver-scaleway/issues/40#issuecomment-217661129 :)
