### ISSUE TITLE
FATA[0009] cannot execute 'run': failed to create server: The sum of volumes sizes of VC1M instances must be between 51GB and 100GB 

### ISSUE THREAD

**Issue by ndarilek** [scaleway/scaleway-cli#360]
Getting this with the latest `go get` as of 5 minutes ago. My command:

```
scw run --name sandstorm2 --commercial-type=VC1M -v 99G Ubuntu_Xenial
```

I've tried with and without `-v`, and it isn't clear if the 51 and 100 are inclusive or not.

Thanks.

**Comment by moul** [comment]
Hi @ndarilek, we are sorry for this annoying issue, this is something quite new,

---

When you start a new server, your image (Docker/Ubuntu/Whaterver) is on a 50GB volume, so when you run `scw run --name sandstorm2 --commercial-type=VC1M -v 99G Ubuntu_Xenial`, you are actually using the `50GB` volume + a secondary empty one of `99GB`, `50+99=149GB`, outside of the limit :)

If you want to start a VC1M machine, I suggest you to use a volume size of 50GB which is the biggest volume you can get for the smallest price

`scw run --name sandstorm2 --commercial-type=VC1M -v 50G Ubuntu_Xenial`

**Comment by moul** [comment]
I just created an issue: #361, so we can at least improve the documentation, and ideally mask this useless complexity

**Comment by nicolai86** [comment]
this error still occurs when -v is omitted:

``` 
$ scw create --commercial-type=VC1M ubuntu-precise
FATA[0000] cannot execute 'create': The sum of volumes sizes of VC1M instances must be between 51GB and 100GB
```
