### ISSUE TITLE
shell: display how to quit

### ISSUE THREAD

**Issue by Codelax** [scaleway/scaleway-cli#3621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To quit shell mode (`scw shell`) you must use Ctrl-D to close stdin. We should display an help when starting the shell.
`scw instance server console` can be used as a reference

**Comment by mgurrie** [comment]
I am interested in working on this issue @Codelax @remyleone Let me know what I need to do to help efficiently.
