### ISSUE TITLE
Remove Available Ingresses from k8s version list and version get

### ISSUE THREAD

**Issue by tgenaitay** [scaleway/scaleway-cli#3630]
Managed Ingresses have been removed after nearly 2 years of deprecation https://www.scaleway.com/en/docs/changelog/?a=kubernetes-33dac6d6-24d0&tags=containers_kubernetes

As such, version list and version get APIs do not return this value anymore https://www.scaleway.com/en/developers/api/kubernetes/#path-versions-list-all-available-versions

This issue to update the cli commands _scw k8s version list_ and _scw k8s version get_ and remove "AVAILABLE INGRESSES" response accordingly.

scw k8s version list

```
NAME     AVAILABLE CNIS                      AVAILABLE INGRESSES  AVAILABLE CONTAINER RUNTIMES
1.28.2   [cilium calico kilo]                -                    [containerd]
...
```

scw k8s version get 1.28.2 

```
Name    1.28.2
Label   Kubernetes 1.28.2
Region  fr-par

Available CNIs:
[cilium calico kilo]

Available Ingresses:
-
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Mia-Cross** [comment]
The field was removed in #3608 and is no longer displayed as of v2.27.0
