### ISSUE TITLE
Create Server with multiple volumes

### ISSUE THREAD

**Issue by nicolai86** [scaleway/scaleway-cli#364]
Hey there,

I'm wondering how to create a server with multiple volumes via the API SDK, for a more complete terraform provider (see [here](https://github.com/nicolai86/terraform/commit/9693f7ecc7ab0b0ed637d36c6cccb863a01de216))
Following [`helpers.go`](https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/helpers.go) it seems that `ScalewayServerDefinition.Volumes` should look like 

```
map[string]string{
  "1":"9d8772e2-64ce-4a18-a2b3-552a2d5379be", 
  "0":"0b6fe93f-2118-4157-81fe-b5a196b1e9da"
}
```

However, when executing `PostServer` I get an error: 

```
{APIMessage:"Validation Error", Type:"invalid_request_error", Fields:map[string][]string{"volumes.0":[]string{"extra keys not allowed"}}, StatusCode:400, Message:""}
```

Any idea on what I'm doing wrong is greatly appreciated. I was assuming that following `helpers.go` would work, but it doesn't.

**Comment by QuentinPerez** [comment]
Hi @nicolai86,

Thanks you for your work, really appreciate 😊.
I take a look at your code and what do you think about using `CreateServer` that you can find [here](https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/helpers.go#L281).
It will be more simple, I used it for [docker-machine](https://github.com/scaleway/docker-machine-driver-scaleway/blob/master/driver/scaleway.go#L245)  
You just need to fill this [structure](https://github.com/scaleway/scaleway-cli/blob/master/pkg/api/helpers.go#L269-L278) 

Let me know if you need anything else.

**Comment by nicolai86** [comment]
Hey @QuentinPerez,

Thanks for the idea! While this might work fine for creating a server, I'd like to follow a path which allows volumes to be changed as well - which is why I'd like to stick to the PostServer api; 

Do you have an idea why the approach above doesnt work? It's the one which should work according to api docs...

**Comment by nicolai86** [comment]
@QuentinPerez I was able to fix my issue myself, after reading the source of the `CreateServer` function you mentioned more closely.

Turns out, when you use an image which is not a snapshot, you leave out `volumes["0"]` - and start directly with `volumes["1"]` for the attached volumes. Tricky!

Thank you.

**Comment by moul** [comment]
@QuentinPerez, can you add a command and a warn in the helper ?

**Comment by nicolai86** [comment]
@moul ideally attaching/ detaching of volumes should he an explicit action, not hidden behind some data structure in a CRUD operation. Would love to see an improved scaleway api for this...

**Comment by nicolai86** [comment]
Thinking about this better error messages would have helped a lot. I already wandered of to changing volumes on an existing server, different topic ;)
