### ISSUE TITLE
Please allow setting the bootscript after create/run

### ISSUE THREAD

**Issue by FlorianHeigl** [scaleway/scaleway-cli#383]
Via your web UI it's just a click plus a reboot.
It's more than just annoying it I can't easily do this from the CLI.
Docker style syntax doesn't have to mean we shoot our brains out by not allowing the most trivial tasks - or at least that's what I was hoping!

**Comment by QuentinPerez** [comment]
Hi @FlorianHeigl 

You can do the following command
```bash
scw _patch SERVER bootscript=BOOTSCRIPT_ID
scw restart SERVER
```

**Comment by FlorianHeigl** [comment]
Wow, will try!

**Comment by FlorianHeigl** [comment]
it worked! 

for others:
create your server
adjust the bootscript in advanced config web interface menu
scw inspect to see the uuid
from then on you can use the uuid with scw _patch and you can do it prior to boot if you

- scw create
- scw _patch
- scw start
