### ISSUE TITLE
scw login

### ISSUE THREAD

**Issue by Codelax** [scaleway/scaleway-cli#3881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new command that allow interactive login using account.scaleway.com.
The account website allow login and response to a callback, CLI would need to host a temporary web server to get the response of the callback.

This feature would fail if:
- CLI cannot open a webserver for callback (cannot bind port).
- CLI is in an isolated environment. Then it should provide an input to user to bypass the interactive login.

An example implementation can be found [here](https://github.com/aerialls/scaleway-cli/commit/bca5ef569f7c5e70b5ec58a0e3c0407e52e96ef9).

### How I imagine scw could expose this functionality

This command could be in `scw account login` and be re-used in `scw init` to improve current workflow.
If login workflow is not possible, it would fallback to actual behavior.

**Comment by quantumsheep** [comment]
To prevent port binding collision issue, we can use the system's automatic port assignment instead of a fixed port.
```go
listener, err := net.Listen("tcp", ":0")
if err != nil {
    panic(err)
}

port := listener.Addr().(*net.TCPAddr).Port

go func() {
	err = http.Serve(listener, nil)
	if err != nil {
		panic(err)
	}
}()
```
