### ISSUE TITLE
"scw login" is not checking the provided organization ID

### ISSUE THREAD

**Issue by cruftex** [scaleway/scaleway-cli#390]
It is possible to login with an invalid organization ID. In fact some of the scw commands work without it, but some give strange errors, which cannot be connected to the wrong organization ID.

## To reproduce

Login via token from the Web UI:

$ scw login -t '56e9cxxxxxxxx' -o 'jw_scaleway@headissue.com' --skip-ssh-key

PS works:

$ scw ps
SERVER ID IMAGE COMMAND CREATED STATUS PORTS NAME COMMERCIAL TYPE
5708a169 Ubuntu_Xenial_16_04_lates 9 days running 163.172.149.246 scw-91e1bd VC1M

images gives error:

$ scw images
FATA[0001] cannot execute 'images': unable to fetch images from the Scaleway API: unexpected end of JSON input 

=>
There is no indication that the organization is wrong.

## Improvement

Check for valid organization ID at login.

**Comment by QuentinPerez** [comment]
Hi @cruftex,

It fixed in the latest version

```
$ scw login -t '56e9cxxxxxxxx' -o 'jw_scaleway@headissue.com' --skip-ssh-key
You are already logged as Quentin Perez
FATA[0000] cannot execute 'login': Unable to contact ScalewayAPI: StatusCode: 401, Type: invalid_auth, APIMessage: Invalid format header 'X-Auth-Token', Details: map[]
```
