### ISSUE TITLE
SCW not sending ssh key to server

### ISSUE THREAD

**Issue by chrisDeFouRire** [scaleway/scaleway-cli#408]
I've used `scw login -o OOOOO -t TTTTT` and I have specified the ssh key to use (more than once, really).

I can `scw create` or `scw start`...

I can use `ssh -i ~/.ssh/<my key> root@<server ip>` and login.

But when I `scw -D exec <my server>`:

- server asks for root password (instead of using key)
- debug prints `DEBU[0002] Executing: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root <server IP> -t -t -p 22 `. There's no sign of `-i`

SCW is as-new, installed from homebrew (`brew install scaleway/scaleway/scw --HEAD`)...

**Comment by QuentinPerez** [comment]
Hi @chrisDeFouRire 

Can you try the following commands ?

```console
$ eval $(ssh-agent -s)
$ ssh-add ~/.ssh/your_key.pub
$ scw exec ...
```

**Comment by chrisDeFouRire** [comment]
```
$ eval $(ssh-agent -s)
Agent pid 40427

$ ssh-add id_scaleway.pub 
Enter passphrase for id_scaleway.pub: 

$ scw exec be1027aa
root@163.172.170.XXX's password: 
```
problem _not_ solved :(

**Comment by chrisDeFouRire** [comment]
I've added `IdentityFile ~/.ssh/id_scaleway` to my `~/.ssh/config` file and it's working now!

Maybe it would be easier if the -i option was passed to ssh, when an ssh key was chosen in `scw login`...
