### ISSUE TITLE
SCW created fantom server

### ISSUE THREAD

**Issue by chrisDeFouRire** [scaleway/scaleway-cli#409]
I've been fighting to get rid of a server, because it appears there's a duplicate name... except there isn't.

```
$ scw ps
SERVER ID           IMAGE               COMMAND             CREATED             STATUS              PORTS               NAME                COMMERCIAL TYPE
be1027aa            bencher                                 About an hour       running             163.172.170.YYY     bench-002           VC1S
a9ecefc3            Docker_1_12_1                           7 hours             running             163.172.166.XXX     bench-001           VC1S
```

When I try using the `bench-002` for anything, there's an error:

```
$ scw stop bench-002
- 0abf0af6          server:bench-002    bench-002           x86_64
- be1027aa          server:bench-002    bench-002           x86_64
FATA[0000] cannot execute 'stop': Too many candidates for bench-002 (2) 
```
and I have to use the ID instead (`be1027aa` in this case).

I don't know exactly what went wrong... I used only scw to create bench-002. At first, the bootscript param wasn't correct (couln't run docker) so I removed the server and recreated it...

I have been unable to remove this fantom server entirely.

**Comment by QuentinPerez** [comment]
Hi @chrisDeFouRire,

The `scw cli` uses a cache system, in this case you can flush it with `scw _flush-cache` but if you have two instances with the same name, you must use the server ID.

**Comment by chrisDeFouRire** [comment]
Thanks @QuentinPerez ! It worked like a charm (there's only one instance with that name)...

_There are only two hard things in Computer Science: cache invalidation and naming things._
