### ISSUE TITLE
terminate an instance

### ISSUE THREAD

**Issue by dcharbonnier** [scaleway/scaleway-cli#415]
What is the correct method to terminate an instance and not archive it ?
This [api.go#L1200](https://github.com/scaleway/scaleway-cli/blob/5801dfefe16e749b2600de765f465701a1a6edd2/pkg/api/api.go#L1200) does not looks to be the correct method according to the ticket DRGAZ301

Related to https://github.com/hashicorp/terraform/issues/9430

**Comment by QuentinPerez** [comment]
Hi @dcharbonnier,

To remove a server without archive it, you have to call `deleteServerSafe`, but it wasn't really explicit, then I rename this method `deleteServerForce` in this [PR](https://github.com/scaleway/scaleway-cli/pull/416)

**Comment by NoKriK** [comment]
Can we close this issue @QuentinPerez ?
Seems to be addressed by your PR.
