### ISSUE TITLE
Downgrade bootscript for existing server

### ISSUE THREAD

**Issue by tgezginis** [scaleway/scaleway-cli#417]
How can i downgrade bootscript for existing server?

**Comment by QuentinPerez** [comment]
Hi @tgezginis 

You can use the CLI but you can't find the old bootscripts.
Can you tell me which bootscript/architecture do you want ?

**Comment by tgezginis** [comment]
Hi @QuentinPerez 

I wanted to downgrade to Linux / Kernel 4.5.1 x64. But i need it to stay now. You can close issue.

Thanks.
