### ISSUE TITLE
New scaleway region is invalid

### ISSUE THREAD

**Issue by tboerger** [scaleway/scaleway-cli#426]
The scaleway provider has launched a new region, but this is currently invalid within the scaleway provider definition because the vendored client is outdated. Since it's not documented how to properly update these libs I need some assistence to fix that.

/cc @nicolai86

**Comment by nicolai86** [comment]
@tboerger I normally copy the files from `scaleway-cli/pkg/` into `vendor/github.com/scaleway/scaleway-cli` and delete the `helpers.go` afterwards.

`helpers.go` pulls in a bunch of dependencies which itself amount of a huge bloat, and we don't need that at all for terraform.

I've long wanted to refactor the scaleway go SDK to remove this, effectivly make a lightweight version of their SDK not bound to their CLI implementation, but didn't find the time yet. It's a bigger undertaking.

Hope this helps! Basically two simple steps to update the SDK on terraforms side :)

**Comment by tboerger** [comment]
And I just realized now that I have posted this issue to the wrong repo, I wanted to post it to terraform of course. Thanks, will give it a try.
