### ISSUE TITLE
scw init on PowerShell

### ISSUE THREAD

**Issue by Monitob** [scaleway/scaleway-cli#4299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Command attempted

`scw init`

### Expected Behaviour

Configuration on Windows Server Core with a simplified interface

### Actual Behaviour

Failed to create client.

## More info

When pasting the information I get constantly an error message.

**Comment by remyleone** [comment]
Cannot reproduce if the copy and paste is working properly. I've try using the right click and it work in my terminal. I will add more information to the validation process.
