### ISSUE TITLE
Please add --ip-address=#id

### ISSUE THREAD

**Issue by flybyray** [scaleway/scaleway-cli#445]
currently only none or dynamic is supported. if there is a ip setting with reverse entry it would be nice to assign it on create or run.

**Comment by 6illes** [comment]
hi @flybyray,
if I well remember it works fine if you specify a reserved ipv4 with quotes ( "xx.xx.xx.xx" ) assuming this ip is not used by another running/stopped instance
becareful though when you restart an instance with an IP or a name that you already used, better flush the cache before
good luck
