### ISSUE TITLE
How to host ASP MVC 5  websites on Scaleaway

### ISSUE THREAD

**Issue by weedkiller** [scaleway/scaleway-cli#447]
Hi I am looking for something like gear host or win host, and saw you might be a good option.

However, there is absolutely NO HELP on hosting a windows ASP MVC website for my company!!!

**Comment by sieben** [comment]
Hello,

This repository is focused on the scaleway-cli project. 
At the moment Scaleway does not support the hosting of Windows machine. However, we support Linux machine and Microsoft made it possible to run ASP MVC application on Linux host.

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/start-mvc

Best regards 

Rémy
