### ISSUE TITLE
Support all instance types in a released version

### ISSUE THREAD

**Issue by Delphinator** [scaleway/scaleway-cli#451]
The current released version v0.11.1 does not support starting servers with the "workload intensive" instance types released [a month ago today](https://blog.online.net/2017/02/23/workload-intensive-cloud-servers-new-variants/).

The version in master (at least judging by [the documentation](https://github.com/scaleway/scaleway-cli#scw-run) seems to support the bigger two (X64-60GB and X64-120GB), but not the intermediate ones (X64-15GB and X64-30GB). It also uses the new names X64-{2|4|8]GB for VC2[S,M,L].

I'd really like to use especially the X64-15GB type in an automation context. Could you release a version of scaleway-cli, that supports creating it via `scw run`?

**On a side note** the names X64-[2|4|8]GB are quite frankly confusing. The bigger instances have Xeon processors, which should perform quite a bit better per core than the Atom processors found in X64-[2|4|8]GB. This is also not really mentioned anywhere besides [the blog post](https://blog.online.net/2017/02/23/workload-intensive-cloud-servers-new-variants/). anouncing X64-[15|30|60|120]GB.

**Comment by Delphinator** [comment]
The version in `master` looks fine now (just by reading the changes in #452). Are there plans for a release soon so distributions can pick this up?

**Comment by brmzkw** [comment]
How did you install scaleway-cli?

If you install it from the sources, just git pull and make install.

If you installed it through homebrew, thennnn... please wait a bit, I'm still trying to figure out how to upgrade the homebrew formulae (I've never done it, @QuentinPerez used to do it but he is unfortunately not working at Scaleway anymore).

**Comment by Delphinator** [comment]
I'm using https://aur.archlinux.org/packages/scaleway-cli/

**Comment by moul** [comment]
@brmzkw fyi, you can install the latest version using homebrew by appending `--HEAD`:

`brew install scw --HEAD`

ps: I don't know how aur works

**Comment by brmzkw** [comment]
Thanks @moul 

#### OSX users

I made a pull request on homebrew: https://github.com/Homebrew/homebrew-core/pull/11846
When it will be merged, `brew upgrade` should bring you the last scaleway-cli version.

Until then, you can still use our custom [brew repository](https://github.com/scaleway/homebrew-scaleway) with `brew tap scaleway/scaleway`

#### Archlinux users

@Delphinator : we did not create the AUR package for Archlinux. If you want to have an updated version of scaleway-cli, you could try to contact the package's maintainer ("moscar").

#### All

scaleway-cli checks from time to time if it is at the last version available. To do so, it makes a HTTP query to one of our servers which returns the latest released version. If it's not, it displays a message saying you are outdated. We will update this file in the next few days to push the update.
