### ISSUE TITLE
CLI uses root password instead of ssh key password

### ISSUE THREAD

**Issue by drunkengranite** [scaleway/scaleway-cli#468]
SCW login works fine, but when using any commands it requires root password, not ssh key password

the .scwrc has the token and organization ID inside of it

it works on logging in with a different user other than root, but does not drop it to the root shell like ssh does. If I have a docker-compose.yml file in root, another user that has root cannot use the file.

Using latest OSX and running it locally (not in the docker container)

mods lemme know if you want me to pm you my stuff

**Comment by gabriel-dehan** [comment]
@drunkengranite I am having the same issue, were you able to resolve it ? Thanks

**Comment by drunkengranite** [comment]
ssh-add, and add the key you use for your servers
