### ISSUE TITLE
scw ps creates a new cache file every time

### ISSUE THREAD

**Issue by princemaple** [scaleway/scaleway-cli#471]
![screenshot](https://user-images.githubusercontent.com/1329716/28096982-28da6156-66f0-11e7-989b-e6147b60bdd8.png)

Every time scw ps creates one more file. And they are identical. (other than the file name)

**Comment by tbillon** [comment]
Fixed by e049e26835373ea655dcf456a8cecb91a41f0898. This will be fixed in the next release. Thank you for your report.

**Comment by princemaple** [comment]
Thank you for the quick fix!

**Comment by princemaple** [comment]
@tbillon any idea when the next release will be made? The milestones are exactly update-to-date.
