### ISSUE TITLE
IPv4 remove from account?

### ISSUE THREAD

**Issue by Dexus** [scaleway/scaleway-cli#474]
does the cli give back not used public IPv4 or need i also to login to the dashboard?

**Comment by tbillon** [comment]
You can get your server IP address from the cli with the command `scw inspect -f "{{ .PublicAddress.IP }}" server_id`.

**Comment by Dexus** [comment]
That was not the question... @tbillon 

What happens when I destroy a server? Will the used IPv4 also removed from the account or is it still in the account and I pay them for not using?

**Comment by tbillon** [comment]
Ah sorry. If you create your server with the cli the IP address will be released when you destroy your server. On the contrary, if you use the dashboard, the IP address is reserved and must be released manually when a server is destroyed.

**Comment by Dexus** [comment]
Thank you for you answer and to clarify the thoughts of mine.
