### ISSUE TITLE
login with 2FA issue

### ISSUE THREAD

**Issue by teuffy** [scaleway/scaleway-cli#481]
Hi 
As recommended by the scw assistance. here is my problem:
Can't login via scw cli. I tried with 2FA disabled and got the same result

```
scw login
Login (cloud.scaleway.com): ####@xxx.org
Password: 
Two-Factor auth token (or backup code): 
FATA[0042] cannot execute 'login': Unable to find your organizatiotion
```

**Comment by teuffy** [comment]
FYI
I can connect following this https://github.com/scaleway/scaleway-cli/issues/390
scw login -t 'mytoken' -o 'myusername@gogo.go'

**Comment by brmzkw** [comment]
Hi,

Can you provide a ticket id? Or your organization, or email?

You can send me the details by email at jcastets@scaleway.com, and we'll continue the discussion here.

**Comment by teuffy** [comment]
Hi Julien,

ticket Id: EPUQ
https://cloud.scaleway.com/#/tickets/EPUQ-9650-DVDV <https://cloud.scaleway.com/#/tickets/EPUQ-9650-DVDV>

Please read my post on github as I solved it.

Thanks for your very  reactive support. I appreciate

**Comment by brmzkw** [comment]
Thanks,

Can you remove your ~/.scwrc file (if it exists) and paste the output of `scw -D login` please?

**Comment by brmzkw** [comment]
Also, can you try with the git version?

**Comment by teuffy** [comment]
Julien,

As per my 2nd post on github, I have been able to logon with

scw login -t “mytoken” -o “myuser” …

Do you know want to do you recom  (delete .scwrc …) for testing purpose?

**Comment by brmzkw** [comment]
Yes, if possible could you remove the ~/.scwrc file then test running `scw login`, and `scw version`?

**Comment by brmzkw** [comment]
Feel free to reopen if there is still an issue.
