### ISSUE TITLE
Billing API

### ISSUE THREAD

**Issue by Alwaysin** [scaleway/scaleway-cli#484]
If I'm not mistaken, it is already a long time this is stated on the FAQ but still not yet available:

> Where is the billing API documentation?
> Our Billing’s API is not public yet. We plan to release it in the coming months.

What are the plans ? The lack of this API is very time-consuming for us IT guys and our accounting department.

**Comment by kdeldycke** [comment]
The whole billing stack is currently being revamped under the scenes. If you want to help me on that, feel free to send your resume at: https://careers.scaleway.com/job/billing-and-payments-software-engineer ! 😃 

In the mean time I welcome all contributions to complement our public API documentation. Feel free to send PRs on https://github.com/scaleway/api.scaleway.com to add a detailed description of billing endpoints.
