### ISSUE TITLE
Add scw cli subcommand to list ip like in web console

### ISSUE THREAD

**Issue by harobed** [scaleway/scaleway-cli#493]
Suggest : add scw cli subcommand to list ip like in web console.

**Comment by tritas** [comment]
Hi, is there any plan to include this enhancement in the v2.0 ?

**Comment by QuentinBrosse** [comment]
Hi @tritas, yes it's planned! 👌

**Comment by QuentinBrosse** [comment]
Hi,

With the [`v2.0.0-beta.1`](https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0-beta.1) release it is now possible to list your instance IPs with:
```
$ scw instance ip list
```

Thanks again for your suggestion. :)
