### ISSUE TITLE
Regression on scw 1.16

### ISSUE THREAD

**Issue by karibou** [scaleway/scaleway-cli#507]
When attaching to the console using scw attach, the output will be displayed correctly but at the first input one gets : 
$ scw attach cloudinit
You are connected, type 'Ctrl+q' to quit.
panic: runtime error: index out of range

goroutine 37 [running]:
github.com/scaleway/scaleway-cli/vendor/github.com/moby/moby/pkg/term.(*escapeProxy).Read(0xc4204bf410, 0xc4200b5080, 0x80, 0x80, 0xc42000e010, 0x0, 0x0)
        /private/tmp/scw-20180421-80517-mwetz6/scaleway-cli-1.16/src/github.com/scaleway/scaleway-cli/vendor/github.com/moby/moby/pkg/term/proxy.go:54 +0x5f5
github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client.(*Client).writeLoop(0xc4200806c0, 0xc4202abfc0, 0x0)
        /private/tmp/scw-20180421-80517-mwetz6/scaleway-cli-1.16/src/github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client/gotty-client.go:352 +0x392
created by github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client.(*Client).Loop
        /private/tmp/scw-20180421-80517-mwetz6/scaleway-cli-1.16/src/github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client/gotty-client.go:238 +0x110

**Comment by brmzkw** [comment]
DUP https://github.com/scaleway/scaleway-cli/issues/499
