### ISSUE TITLE
Error with ERPNext installation

### ISSUE THREAD

**Issue by hfaridgit** [scaleway/scaleway-cli#515]
I have error with new versions of ERPNext installation on Ubuntu 16.04 on scaleway VPS servers
I got error on localectl  command, you can try the command type it on the server command line and you will get error message.
$ localectl
Could not get properties: Connection timed out

Please help and solve this issue as we can't install ERPNext any more on your servers.

**Comment by remyleone** [comment]
Hello,
It seems that this issue does not concern the CLI directly. I would suggest opening a ticket on the console: https://console.scaleway.com/support/tickets
