### ISSUE TITLE
Create/Handle standalone volumes without instantiating any server

### ISSUE THREAD

**Issue by piroux** [scaleway/scaleway-cli#518]
It is currently possible to create a server and add a second volume, _but if I am not mistaken_, **`scw` cannot create standalone volume, so that it has to be done from the Scaleway dashboard**.

Actually, I think that from the `scw` binary, it would be great if we could have the ability to:
- create a volume
- delete a volume
- list all volumes
- get volume details directly

like the [Volume API](https://developer.scaleway.com/#volumes).

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

**Comment by remyleone** [comment]
For this particular issue, I would invite you to take a look at `scw instance volume` :)
