### ISSUE TITLE
on osx the completion script output an error at shell init

### ISSUE THREAD

**Issue by waxzce** [scaleway/scaleway-cli#519]
`-bash: complete: noquote: invalid option name`

**Comment by espen-jervidalo** [comment]
In ```/usr/local/etc/bash_completion.d/scw.bash``` in the very last line remove ```-o noquote``` and it goes away. 
Thanks for the pointer, has been annoying me for a while.

```
$ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```
And bash-completion 1.3_3 installed from homebrew.

**Comment by TRex22** [comment]
+1 Im getting this too. Its really annoying to have to edit the completion file every time I update my local packages

**Comment by jonathan-vouch** [comment]
Thank you for fixing @tw3n :) I've only just found out it was `scw` causing this extremely annoying issue the whole time and I'm glad you've PR-ed the fix!
