### ISSUE TITLE
documentation error for "scw stop"

### ISSUE THREAD

**Issue by jfyuen** [scaleway/scaleway-cli#523]
The Readme for `scw stop` has an example `$ scw stop server && stop wait server`.
Shouldn't it be `$ scw stop server && scw wait server` ?

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.
