### ISSUE TITLE
Reorganization of scw cli

### ISSUE THREAD

**Issue by Sh4d1** [scaleway/scaleway-cli#525]
After seeing #518 and the upcoming release of object storage I think it would be nice to separate `scw` commands into sub commands like:
- scw server
  - attach
  - create
  - start
  - ...
- scw volume
  - create
  - ls
  - rm
  - ...
- scw bucket
  - ls
  - ...
- ...
  
Or, to follow docker cli, have the server commands as main commands (like right now) but add sub commands for volumes, images, buckets, ...
What do you think?

**Comment by kindermoumoute** [comment]
We are working on a new version of the CLI to support all the new coming products. Stay tuned! ;-)
