### ISSUE TITLE
Default to current directory for scw cp if no path is specified

### ISSUE THREAD

**Issue by jfyuen** [scaleway/scaleway-cli#527]
A path must always be specified for `scw cp`, even if copying to the user default directory (`.`) on the remote server.

Support for empty path, which would mean `.` by default, just like for scp, would be useful.

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.
