### ISSUE TITLE
quota exceeded

### ISSUE THREAD

**Issue by ker2x** [scaleway/scaleway-cli#530]
### Problem

When you have exceeded your quota you have an error like this one : 
```
FATA[0001] cannot execute 'create': StatusCode: 403, Type: invalid_request_error, APIMessage: Quota exceeded for this resource. 
```

But we don't know what "this" ressource is.

### Example of expected result

FATA[0001] cannot execute 'create': StatusCode: 403, Type: invalid_request_error, APIMessage: Quota exceeded for resource : ip, server, volume, ...

**Comment by nathan-K-** [comment]
Same here,
Quite critical issue

**Comment by hazcod** [comment]
I have the same error for creating `C2S` instances. Contacted support.

**Comment by hazcod** [comment]
@ker2x in my case it was because they stopped offering API access to `VC1S` instances, in favor of their new instances..

**Comment by jerome-quere** [comment]
Hi, 

As @hazcod explains, some old server types are being deprecated and new customers cannot create this type of server anymore.

Unfortunately by default `scw create` is configured to create a deprecated server type. This will be fixed soon as we will change the default to DEV1-S.

In the meantime, you can use the `--commercial-type` option to select a new server type.

I will close this issue, if you have further question do not hesitate to re-open it.

**Comment by Dav2015** [comment]
Having the same issue, not able to create a Apple Silicon. My Billing are up to date and, verified??

**Comment by AlluraRed** [comment]
@Dav2015 2015 Did you fix it?
