### ISSUE TITLE
scw inspect doesn't work if "-" hyphen is present in name

### ISSUE THREAD

**Issue by alexellis** [scaleway/scaleway-cli#531]
I created an image named `inlets-4a0817ff` and `scw inspect` cannot find that server with any of the following:

```
scw inspect inlets-4a0817ff # doesn't work
scw inspect server:inlets-4a0817ff # doesn't work
scw inspect server"inlets-4a0817ff" # doesn't work

# renaming to inlets4a0817ff # allows the following to work
scw inspect inlets4a0817ff # works
```

It works on `scw exec` so I assume there might be an issue with the args-parsing code for `scw inspect`.

Please could someone look into this and get back to me?

**Comment by alexellis** [comment]
Might be related to #473 ?

**Comment by phhusson** [comment]
As mentioned in https://github.com/scaleway/scaleway-cli/issues/473; `rm ~/.scw-cache.db` "fixes" the issue

**Comment by alexellis** [comment]
This is not a fix, it is a manual and (unfortunately) impractical workaround

**Comment by QuentinBrosse** [comment]
Hi @alexellis,

**Comment by Hades32** [comment]
Can reproduce:
```
$ scw version
Client version: v1.20
Go version (client): go1.13
Git commit (client):
OS/Arch (client): windows/386
```

The above workaround helped, but...

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.
