### ISSUE TITLE
Homebrew scaleway/scaleway tap is broken

### ISSUE THREAD

**Issue by dkhamitov** [scaleway/scaleway-cli#533]
While following the [Setup procedure](https://github.com/scaleway/scaleway-cli/tree/8c7c75ebf3349d29fcaf8464daf42a7270dd546d#setup), I came across an error in the brew formula for [scw](https://github.com/scaleway/homebrew-scaleway/blob/ff085eadf97e43d1e41bb7c67667dd264d036e1a/scw.rb) from ```scaleway/scaleway``` tap. It fails at ```bash_completion.install``` step. The [fix](https://github.com/scaleway/homebrew-scaleway/pull/10) is trivial and waiting. But I'm curious why that tap is necessary? Isn't just ```homebrew-core``` [scw](https://github.com/Homebrew/homebrew-core/blob/de1ecc1d981de9d5165ea9e96242c32023d14d7c/Formula/scw.rb) enough?

**Comment by QuentinBrosse** [comment]
Hi,

The brew tap support has been removed and only the `homebrew-core` ([scw](https://github.com/Homebrew/homebrew-core/blob/master/Formula/scw.rb))version will be maintained.
The [setup instructions has](https://github.com/scaleway/scaleway-cli#setup) also been updated.

You can find the related work here:
- https://github.com/scaleway/homebrew-scaleway/pull/12
- https://github.com/scaleway/scaleway-cli/pull/560
