### ISSUE TITLE
Server disappear from ps after stop

### ISSUE THREAD

**Issue by Matteounitn** [scaleway/scaleway-cli#545]
Hello. I find out if you write `scw stop <serverid>` or `scw stop <servername>`, the server will disappear from ps list, but it's bootable with `scw start <serverid>` or `scw start <servername>`

Step to reproduce:

1. Start a server with console.scaleway.com
2. connect with scw cli to your account
3. `scw stop` followed by your server id
4. when entirely stopped, `scw ps`. Server won't be there.

**Comment by QuentinBrosse** [comment]
Hello and thanks for this report.
By default, only running servers are displayed with `scw ps`. If you want to show all servers, whatever their status, use `scw ps -a`.

You can find all this information with the `scw ps --help` command. The `--help` flag is available for all other commands too.

Does it answer your question? 🙂

**Comment by Matteounitn** [comment]
> Hello and thanks for this report.
> By default, only running servers are displayed with `scw ps`. If you want to show all servers, whatever their status, use `scw ps -a`.
> 
> You can find all this information with the `scw ps --help` command. The `--help` flag is available for all other commands too.
> 
> Does it answer your question? slightly_smiling_face
Thank you for the clarification.
I thought differently because I can see my "stopped in place" server, i thought i could see them all with `scw ps`. Sometimes i can see all my server with `scw ps`. I mean, i have a stopped server besides the main one and i can always see it with `scw ps`. Is this on purpose?

**Comment by QuentinBrosse** [comment]
Some server actions are asynchronous, it is the case of `start` and `stop` for example. Therefore, if you stop a server and list servers just after (cf. `scw stop {id} && scw ps`) you will still see your server in the list because it is stopping and is not stopped yet. That's why you have a `STATUS` column in the `scw ps` command to see the exact status of the instance.

Note that you can use the [wait command](https://github.com/scaleway/scaleway-cli#scw-wait) to wait until a server stops.

## Example

I have a running server:

```bash
➜  ~ scw ps
SERVER ID           IMAGE                  ZONE                CREATED             STATUS              PORTS               NAME                   COMMERCIAL TYPE
f97569e5            Ubuntu_Bionic_Beaver   par1                23 minutes          running             51.158.65.149       scw-youthful-feistel   START1-S
```

I stop it:

```bash
➜  ~ scw stop f97569e5
f97569e5
```

I list my server directly after (note the `stopping` status):

```bash
SERVER ID           IMAGE                  ZONE                CREATED             STATUS              PORTS               NAME                   COMMERCIAL TYPE
f97569e5            Ubuntu_Bionic_Beaver   par1                27 minutes          stopping            51.158.65.149       scw-youthful-feistel   START1-S
```

I list my server a few seconds after (when the server is stopped). The server is not displayed yet:

```bash
➜  ~ scw ps
SERVER ID           IMAGE                  ZONE                CREATED             STATUS              PORTS               NAME                  COMMERCIAL TYPE
```

I list my server with all option and the server is displayed (note the `stopped` status):

```bash
➜  ~ scw ps -a
SERVER ID           IMAGE                  ZONE                CREATED             STATUS              PORTS               NAME                   COMMERCIAL TYPE
f97569e5            Ubuntu_Bionic_Beaver                       32 minutes          stopped             51.158.65.149       scw-youthful-feistel   START1-S
```

If it's clear for you I will close this issue. :)

**Comment by Matteounitn** [comment]
uhm yeah i got it but here is what i have when i wrote `scw ps`:
```
scw ps
SERVER ID           IMAGE                       ZONE                CREATED             STATUS              PORTS               NAME                COMMERCIAL TYPE
xxxxxxxx            Ubuntu_Xenial_16_04_lates   par1                13 months           stopped in place                        scw-yyyyyyy          VC1S

```
As you can see it's stopped but it is still visible, even if it's stopped! (i removed server ID and server name on purpose).
If i execute: `scw ps -a`
```
scw ps -a
SERVER ID           IMAGE                       ZONE                CREATED             STATUS              PORTS               NAME                COMMERCIAL TYPE
zzzzzzzzz                                                            5 days              stopped             XX.XX.XXX.XX        scw-ccccccc       C2S
xxxxxxxx            Ubuntu_Xenial_16_04_lates   par1                13 months           stopped in place                        scw-yyyyyyy          VC1S

```
(i have also censored on purpose server id , server name and server ip).

**Comment by QuentinBrosse** [comment]
Sorry I didn't notice that you are speaking of the `stopped in place` specific status.

I have asked internally and this behavior is on purpose, the `scw ps` command shows all the instances that you are currently charged for (eg. `running` and `stopped in place` status). We don't want to hide this status in the `-a` flag to avoid bad surprises to our clients. :)
