### ISSUE TITLE
Pasting text from clipboard skips characters

### ISSUE THREAD

**Issue by albertoxamin** [scaleway/scaleway-cli#548]
I have this in my clipboard
```
ThisCouldBeATokenICopied
```
When I paste it in scw this is what gets in the terminal
```
TsCouldBeATokenICopied
```
This doesn't happen via ssh

**Comment by kindermoumoute** [comment]
What version of the CLI are you using?

**Comment by albertoxamin** [comment]
scw version v1.17, build

**Comment by albertoxamin** [comment]
I just updated to 1.19
```
Client version: v1.19
Go version (client): go1.12.1
Git commit (client): homebrew
OS/Arch (client): darwin/amd64
```
Problem persists

**Comment by QuentinBrosse** [comment]
I can't reproduce the problem. Can you provide precise steps to reproduce?

**Comment by albertoxamin** [comment]
@QuentinBrosse 
![steps](https://thumbs.gfycat.com/FarBlissfulLeafbird-size_restricted.gif)

**Comment by QuentinBrosse** [comment]
Hi,

I can't reproduce the bug either in `zsh` nor in `bash`. Which terminal do you use? Can you please try to reproduce the bug in a more standard one like `terminal` or `iTerm` (in macOS) and with a default profile (to avoid custom config)?

Thanks for your help.

**Comment by albertoxamin** [comment]
The terminal is iTerm 2 default profile, I get this even with the default terminal

**Comment by QuentinBrosse** [comment]
Ok, so it's not a terminal issue. I could be a network issue.

We are working on a new version of the CLI to support all the new coming products so if the `scw exec` command does the job for you I will close it. Stay tuned ;-)

**Comment by albertoxamin** [comment]
@QuentinPerez It behaves that way in every network I tested, home and university.

`scw exec` doesn't accept my password, that's strange because it is the same I use to login with root using `scw attach`
