### ISSUE TITLE
Include checksums for releases

### ISSUE THREAD

**Issue by thorerik** [scaleway/scaleway-cli#549]
I'm maintaining a chocolatey package for [scaleway cli](https://chocolatey.org/packages/scaleway-cli)

I'd like to see if you could please include checksums for each release as a part of the build artifacts?

That'd make it possible to easily make a self-updating package using au and appveyor as I'd be able to obtain the hashes necessary more easily.

Thanks for the great work you guys are doing 👍

**Comment by QuentinBrosse** [comment]
Hi,

What do you think to this format ? https://github.com/scaleway/scaleway-cli/releases/tag/v1.16 
We could include it in our release process.

**Comment by thorerik** [comment]
would work, but even better would be if there was a matching .sha256sum file accompanying each file.
Though I realize this could be cumbersome to maintain.

**Comment by remyleone** [comment]
@thorerik Would this file be enough: https://github.com/scaleway/scaleway-cli/releases/download/v2.0.0-beta.4/SHA256SUMS

Would you need anything else from us to be able to manage the v2 release that will happen in the upcoming weeks in chocolatey?

**Comment by thorerik** [comment]
It looks like you are deprecating x86 in favour of only x86_64 binaries, is that correct?

**Comment by remyleone** [comment]
Hello @thorerik we added 32 bits support for Windows and Linux: https://github.com/scaleway/scaleway-cli/pull/1115 
What would be required from our side for the release? Do you need any help? We plan to do the release in the upcoming days.

**Comment by thorerik** [comment]
All is good from you, I'm just having to hold off merging changes until after the release to avoid having the automatic build error over and over due to the changes I had to make in regards to supporting the 2.0.0 milestone here :)

**Comment by jerome-quere** [comment]
Hello @thorerik FYI the tag v2.0.0 is planned on Wednesday 😉
