### ISSUE TITLE
Authentication error with 1.19

### ISSUE THREAD

**Issue by anacrolix** [scaleway/scaleway-cli#552]
I'm able to use scw with 1.17, but not 1.19. 1.19 gives:
```
$ scw ps
FATA[0002] cannot execute 'ps': Unable to fetch servers from the Scaleway API: StatusCode: 401, Type: invalid_auth, APIMessage: Authentication error
```
1.17 works fine.

**Comment by jerome-quere** [comment]
Hi,

Could you try: `$> scw login` to make sure the file `~/.scwrc` is up to date.

**Comment by anacrolix** [comment]
Yes I've tried that, thanks.

**Comment by kindermoumoute** [comment]
Closing the issue as it seems to be resolved. Feel free to reopen it if it's not.
