### ISSUE TITLE
inspect: Automatically detect region unless explicitly specified

### ISSUE THREAD

**Issue by abitrolly** [scaleway/scaleway-cli#554]
Right now the UX us the following:
```
$ cli ps   
SERVER ID           IMAGE                  ZONE                CREATED             STATUS              PORTS               NAME                COMMERCIAL TYPE
cc4dca3f            Ubuntu_Bionic_Beaver   ams1                2 weeks             running             51.15.69.159        xe3                 ARM64-2GB

$ cli inspect server:xe3
ERRO[0001] Unable to resolve identifier server:xe3      
FATA[0001] cannot execute 'inspect': at least 1 item failed to be inspected 

$ cli inspect --region=ams1 server:xe3
[{
  "arch": "arm64",
  "id": "cc4dca3f-bd21-4632-ab03-1eaba3ccd0e3",
  "name": "xe3",
...
```
The desired behaviour is to make `cli inspect` search all zones by default without explicit region specifier.

**Comment by remyleone** [comment]
This issue is related to a legacy version of the CLI. We released a new version for the CLI that you can try out: https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0
If your issue is not resolved with this new version, feel free to open a new issue.

**Comment by abitrolly** [comment]
@remyleone do you know if ScaleWay fixed issue that it was impossible to software reboot ARM servers?

**Comment by abitrolly** [comment]
Without this issues fixed, ScaleWay is a no go for me, and testing its new CLI doesn't make sense.
