### ISSUE TITLE
Specifying IP Location While Adding From CLI

### ISSUE THREAD

**Issue by yigitkonur** [scaleway/scaleway-cli#555]
**scw _ips --new** only creates IP in Paris location but not creating IP for Amsterdam. There should be an option to specify the location for the new IPs. Otherwise it only works for Paris datacenters.

**Comment by yigitkonur** [comment]
+ **scw _ips** only lists the Paris IPs.

**Comment by kindermoumoute** [comment]
Not on my laptop right now, but have you tried `scw --region=ams1 _ips --new` ?

**Comment by yigitkonur** [comment]
Thanks a lot! I did not consider to use a default location. Fixed.
