### ISSUE TITLE
Switch to ~/.config/scw/config.yaml

### ISSUE THREAD

**Issue by abitrolly** [scaleway/scaleway-cli#558]
`scw` [uses](https://github.com/scaleway/scaleway-cli/blob/master/pkg/config/config.go) outdated v1 config file format https://github.com/scaleway/scaleway-sdk-go/blob/master/scw/README.md

Are there any plans for new `config.yaml` for compatibility with [other tools](https://github.com/terraform-providers/terraform-provider-scaleway/blob/master/website/docs/index.html.markdown#shared-configuration-file)?

**Comment by kindermoumoute** [comment]
Yes!

We are actively working on a new CLI, which will use new config file format and all new products.

**Comment by abitrolly** [comment]
@kindermoumoute is there any Docker image to test?

**Comment by kindermoumoute** [comment]
@abitrolly not yet, early version should be available by september.

**Comment by QuentinBrosse** [comment]
Hi,

The [`v2.0.0-beta.1`](https://github.com/scaleway/scaleway-cli/releases/tag/v2.0.0-beta.1) is now released. You can find it in the [v2 branch](https://github.com/scaleway/scaleway-cli/tree/v2) of the repository. This new version uses the new `config.yaml` file.

Thanks again for your suggestion. :)
