### ISSUE TITLE
need CLI command to assign/release flexible IP to/from intance

### ISSUE THREAD

**Issue by huglester** [scaleway/scaleway-cli#577]
Currently we cant release IP from server1 
and assign it to server2

can you add such funcitonality?

thanks

**Comment by QuentinBrosse** [comment]
We are working on a new version of the CLI, totally rewritten. It will support all our products and more features including the one that you ask.

In the meantime, you can do it with the [console](https://console.scaleway.com).

Note that if this is an automation use-case, you can use our Terraform provider. A [new version](https://github.com/terraform-providers/terraform-provider-scaleway/issues/125) will be released very soon.
