### ISSUE TITLE
Bug: scw exec wrongly appends a \r char to the output

### ISSUE THREAD

**Issue by benjamin-thomas** [scaleway/scaleway-cli#580]
- Version: scw version v1.20, build (amd64 binary build)
- Binary file info: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
- OS: Ubuntu 16.04.6 LTS
- fileformat=unix (vim editor)

---

This bug drove me crazy. Reproducible with running a script from a file, or via an interactive shell (code below).

```bash
MYVAR=$(scw exec my_server_name echo hello)
echo ">$MYVAR<"
```

Outputs:

    <hello

Because the actual value returned by scw exec is in fact `hello\r`.

So the output get mangled, causing problems when concatenating strings, to construct other vars, etc.

Temporary fix in bash for anyone interested:

    MYVAR=${MYVAR%[[:cntrl:]]}

**Comment by QuentinBrosse** [comment]
Hi @benjamin-thomas,

In your case, `scw` use these command internally:
```bash
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l root <IP> -t -t -p 22 -- /bin/sh -e -c "\"echo hello\""
```

The `-t -t` force the SSH TTY allocation. Like it is explained [here](https://unix.stackexchange.com/a/264042):
> With initializing, the terminal will translate newline (\n) to carriage-return and line-feed (0x0d, 0x0a)

I have just made #583 to add a `--no-tty` allocation. This flag will fix your issue:

```bash
bash-3.2$ MYVAR=$(scw exec -w cli-srv-happy-ptolemy echo hello) && echo ">$MYVAR<"
<hello
bash-3.2$ MYVAR=$(scw exec --no-tty -w cli-srv-happy-ptolemy echo hello) && echo ">$MYVAR<"
>hello<
```

**Comment by benjamin-thomas** [comment]
Sounds great :)
