### ISSUE TITLE
create image has no way of disabling fuzzy match

### ISSUE THREAD

**Issue by Hades32** [scaleway/scaleway-cli#581]
When I use a complete image name that is contained in other image names I get this:
```
marti@Mr-Surface MINGW64 ~/dev/scw-k8s
$ scw create Ubuntu_Bionic
  IMAGEID           FROM                          NAME                    ZONE                ARCH
- 5f96d290          image:ubuntu-bionic-ml-10-1   Ubuntu Bionic ML 10.1   par1                x86_64
- 6bd566a1          image:ubuntu-bionic-ml-9-2    Ubuntu Bionic ML 9.2    par1                x86_64
- f974feac          image:ubuntu-bionic           Ubuntu Bionic           par1                x86_64
←[31mFATA←[0m[0000] cannot execute 'create': Too many candidates for Ubuntu_Bionic (3)
```

The only way out is to use the IMAGEID which is very ugly. 

I'd suggest using `image:Ubuntu_Bionic` to indicate a complete image name that must match exactly.

**Comment by QuentinBrosse** [comment]
Hi @huglester ! :)

We are working on a new version of the CLI, totally rewritten. It will support all our products and more features including the one that you ask.

This issue will be addressed by a well defined and unique image label. `ubuntu-bionic` in your case.

Note that if this is an automation use-case, you can use our Terraform provider. A new version will be released very soon.
