### ISSUE TITLE
restrict token access

### ISSUE THREAD

**Issue by enys** [scaleway/scaleway-cli#792]
Started using the cli, that works great, thanks.

Is there a way to limit the scope of the tokens ?

Ie at minimum generate a read vs read/write token ?

**Comment by loicbourgois** [comment]
Hi @enys, 

This feature does not exist for now. Not in the CLI, the SDK, the Console, nor the API. 

The team in charge of this feature intends to add it, but we do not have an ETA yet. 

Happy you find the CLI useful.
Cheers,

**Comment by enys** [comment]
Thanks for the quick reply @loicbourgois.
This would be a great feature!

Closing for now as their is no ETA, please de feel free to re-open.
