### ISSUE TITLE
[v2] instance volume list shows only l_ssd per default

### ISSUE THREAD

**Issue by hex2a** [scaleway/scaleway-cli#793]
`scw instance volume list` lists only volumes with volume-type `l_ssd`, to list `b_ssd` volumes, a filter must be explicitly specified (`scw instance volume list volume-type=b_ssd`)

**expected behaviour**:
`scw instance volume list` should list all volumes if no filter is specified, as documented in the usage examples (`-h`):
```
EXAMPLES:
  List all volumes
    scw instance volume list

  List all block storage volumes
    scw instance volume list volume-type=b_ssd

  List all local storage volumes
    scw instance volume list volume-type=l_ssd
```

this occurred with the current v2 branch (fc15e97988a223d21ee21e15da2d009e10c7d998)

**Comment by Sh4d1** [comment]
I bumped into a similar issue yesterday, I think it's the sdk's fault 🤔

**Comment by Sh4d1** [comment]
@hex2a https://github.com/scaleway/scaleway-sdk-go/issues/360

**Comment by Sh4d1** [comment]
Fixed on the SDK, so it's fixed here. @hex2a should work now
