### ISSUE TITLE
Add .dockerignore

### ISSUE THREAD

**Issue by loicbourgois** [scaleway/scaleway-cli#809]
*Problem*

While building docker image during release process, we had the following log line :

> Sending build context to Docker daemon  99.61MB 

*Proposal*

Add a `.dockerignore`

**Comment by Sh4d1** [comment]
Folders/files to keep are 
- cmd
- internal
- scripts
- .git
- go.mod
- go.sum

**Comment by Sh4d1** [comment]
Closed via #910
