### ISSUE TITLE
attaching to serial console is not working

### ISSUE THREAD

**Issue by RaitoBezarius** [scaleway/scaleway-cli#882]
Whenever I try to do `scw attach` or `scw run --attach`, it attaches to nothing, i.e. "You are connected", wait some seconds and return the shell.
I'm trying to make work https://github.com/moul/scaleway-ipxe to have NixOS install through iPXE, but I have this error:

```
spawn slow-stream --raw -b 1 -i 10 --stdout-passthrough -- scw run --attach --commercial-type=VC1S 50G
You are connected, type 'Ctrl+q' to quit.
panic: provided file is not a console

goroutine 40 [running]:
github.com/scaleway/scaleway-cli/vendor/github.com/containerd/console.Current(...)
	vendor/github.com/containerd/console/console.go:67
github.com/scaleway/scaleway-cli/vendor/github.com/moul/gotty-client.(*Client).Loop(0xc00044a380, 0x0, 0x0)
	vendor/github.com/moul/gotty-client/gotty-client.go:313 +0x302
github.com/scaleway/scaleway-cli/pkg/utils.AttachToSerial.func1(0xc00044a380, 0xc00022c4e0)
	pkg/utils/utils.go:221 +0x2d
created by github.com/scaleway/scaleway-cli/pkg/utils.AttachToSerial
	pkg/utils/utils.go:220 +0x369
ERRO[0000] exit status 2                                
send: spawn id exp4 not open
    while executing
"send   "\x02""
    (file "./scw-ipxe.expect" line 27)
```

I'm not sure how to diagnose this.

**Comment by Sh4d1** [comment]
Hello @RaitoBezarius ! After some digging it looks like it's because of changes in some vendors. Version 1.19 still works so I encourage you to use this version intead of the 1.20 if you want to make it work. Tough it's an issue on moul/gotty-client not on the cli itself. I'll try to fix it if I find some time though!

**Comment by Sh4d1** [comment]
@RaitoBezarius need https://github.com/moul/gotty-client/pull/77 merged then we'll bump the dep on the cli :)

**Comment by RaitoBezarius** [comment]
Thank you a lot for your fast response (& fix), @Sh4d1 I really appreciate it :)
