### ISSUE TITLE
Add timeouts used by sync commands

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway/scaleway-cli#9]
The following command:

* scw start --sync

Can hang forever if there's a boot issue ; in some scenarii, it is nice to have the ability to set timeouts:

- one for the API state of the server to become OK
- one for the SSH port to be open

These timeouts could be disabled by default, and enabled via CLI options or environment variables or via the config file.

**Comment by moul** [comment]
What would be nice default timeout values for you ?

**Comment by aimxhaisse** [comment]
By default I think it is fine to wait forever

**Comment by aimxhaisse** [comment]
https://github.com/docker/docker/issues/1905

Maybe this can give us ideas

**Comment by aimxhaisse** [comment]
(their solution is to handle this with external tools, I'm fine with this too)

**Comment by moul** [comment]
I personally prefer to add an option for this, but I can let the forever behaviour as a default

**Comment by aimxhaisse** [comment]
:ok_hand:

**Comment by moul** [comment]
Added timeout support for `scw exec`
