### ISSUE TITLE
Support autocompletion in container

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#938]
The issue with running the CLI container is almost 100% problem with the autocomplete.

Propostion:

In the bash script, we print a message `bash-completion must be install` if we detect that this is not the case

Avoid a crash by adding an if condition in the bash script snippet

actual code snippet

```bash
_scw() {
	_get_comp_words_by_ref -n = cword words	output=$(scw autocomplete complete bash -- "$COMP_LINE" "$cword" "${words[@]}")
	COMPREPLY=($output)
	# apply compopt option and ignore failure for older bash versions
	[[ $COMPREPLY == *= ]] && compopt -o nospace 2> /dev/null || true
	return
} 
```

**Comment by jerome-quere** [comment]
We could also update docker-compose to make sure correct bash dependencies are installed and loaded
