### ISSUE TITLE
Add homebrew integration for v2 GA

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#946]
- Do we want to do a TAP ?
  - Probably not we are already in brew native package we should stay there
- Do we support v1 and v2 at the same time
  - I want `brew install scw` to install v2
  - If possible and not too complicated support a `scw@1` in brew core repo
  - If not possile keep a tap for v1? (We already have a tap repo)

**Comment by jerome-quere** [comment]
https://github.com/Homebrew/homebrew-core/pull/57158
