### ISSUE TITLE
Batch delete in cli

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#954]
It would be nice to allow batch delete with the CLI, and just give a list of IDs
—

I would extant this issue to:

Do we need batch commands somewhere else?
If yes how could we handle it without manual code for each command
-----------------------

Proposition:

```go
return &core.Command{
   PositionalList: true, <=============
   ArgSpecs: core.ArgSpecs{
      {
         Name:       "image-id",
         Required:   true,
         Positional: true,
      },
      core.ZoneArgSpec(scw.ZoneFrPar1, scw.ZoneNlAms1),
   }, 
```

If this flag is set to true

Usage should say that positional is a list
The run function should be called once for each of the positional parameters

Could be useful on every delete commands, also in action that does not take any parameters (stop instance, reboot instance, reboot k8s node, replace k8s node, start an instance, snapshot volume, ...)

**Comment by jerome-quere** [comment]
This has been solved with multi positional parameters
