### ISSUE TITLE
Nested object arguments are not being reflected correctly

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#958]
`strcase.ToPublicGoName` is called on the name with a dot in it (eg default-pool-config.node-type ) and thus it's not being reflected correctly (first letter of the word after the dot in not being correctly uppercased)

@Sh4d1 propose a helper function in core that loops over the arg name, and calls `strcase.ToPublicGoName` for each word between dots

**Comment by jerome-quere** [comment]
Not enough detail
