### ISSUE TITLE
Having a scw infos that dump where the configuration is found

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#978]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment I don't have a clear way to know where my configuration come from. Let's suppose that I got a token defined in an environment variable and another defined in the configuration file, I don't have much help to figure out which one is currently being used while doing a request. This could be error-prone in the case where several projects with different identifiers are used concurrently.

### How I imagine scw could expose this functionality

`scw infos`

This will show me a detailed report of the current location of all data that I use, where they are fetched from.

**Comment by jerome-quere** [comment]
```
$> scw infos
config_path               ~/.config/scw/config.yaml
default_region            fr-par     SCW_SECRET_KEY env
default_zone              fr-par-1   config_file
default_organization_id   193-XXXX   config_file
access_key                SCWXXXXX   SCW_ACCESS_KEY env
secret_key                193-XXXX   config_file
profile                   default    flag | SCW_PROFILE | config_file
```

```
KEY: 
  - config_path
  - default_region
  - default_zone
  - default_organization_id
  - access_key
  - secret_key
  - profile

Value:
  - All value are print ( Mask part of secret key )
  - Use `-` if no value found

Origin:
  - env (SCW_XXXXX)
  - config_file
  - flag (-p)
```
