### ISSUE TITLE
Have a login command

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-cli#989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a user I want to have the possibility to do a `scw login`, that will open a page on the scaleway console I can consent to use a token. Have the CLI authenticated and ready to go.

### How I imagine scw could expose this functionality

`scw login`

### References

Many CLI offer such feature

**Comment by thijslemmens** [comment]
One of the major problems we have with the current authentication method is that you need a access_key and secret_key on your workstation. The consequences can be pretty high when the machine gets compromised.

To partially mitigate this, I implemented an initialization tool that automates making a short lived API key and initializes the scaleway cli for you:
https://github.com/xenit-eu/scw-2fa-init

Ideally an OAuth2 based solution would be built in the cli itself.
